security:
  oidc:
    secret: regions-oidc-super-secret
    clientId: regions
    discoveryUri: ${common.protocol}://auth.${common.domain}/cas/oidc/.well-known
    enabled: 'false'
  cas:
    bypass: 'false'
    casServerLoginUrl: ${common.protocol}://auth.${common.domain}/cas/login
    casServerLogoutUrl: ${common.protocol}://auth.${common.domain}/cas/login
    logoutUrl: ${common.protocol}://auth.${common.domain}/cas/logout
    enabled: 'true'
    casServerUrlPrefix: ${common.protocol}://auth.${common.domain}
casServerName: ${common.protocol}://auth.${common.domain}
casServerLoginUrl: ${common.protocol}://auth.${common.domain}/cas/login
casServerUrlPrefix: ${common.protocol}://auth.${common.domain}/cas
casProperties: casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilter,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath

grails:
  serverURL: ${common.protocol}://regions.${common.domain}
uriExclusionFilterPattern: /images.*,/css.*,/js.*,/less.*,/vendor.*
breadcrumbParent: ${common.protocol}://www.${common.domain}/explore-by-location/,Explore
alertsResourceName: Atlas
skin:
  homeUrl: ${common.protocol}://www.${common.domain}
  layout: ala
  fluidLayout: 'true'
#default:
#  region: Flanders
#  regionType: ''
google:
  apikey: get-a-google-api-key

showNotesInfoInAccordionPanel: 'false'
serverName: ${common.protocol}://regions.${common.domain}
disableCAS: 'false'
uriFilterPattern: /admin/*,/alaAdmin/*
orgNameLong: Vlaams Biodiversiteitsportaal

headerAndFooter:
  baseURL: ${common.protocol}://branding.${common.domain}
ala:
  baseURL: ${common.protocol}://${common.domain}
bie:
  baseURL: ${common.protocol}://species.${common.domain}
  searchPath: /search
biocache:
  baseURL: ${common.protocol}://biocache.${common.domain}
  enableQueryContext: 'false'
  queryContext: ''
spatial:
  baseURL: ${common.protocol}://spatial.${common.domain}
images:
  baseURL: ${common.protocol}://images.${common.domain}
layersService:
  baseURL: ${common.protocol}://spatial.${common.domain}/ws'
alerts:
#  baseURL: ${common.protocol}://alerts.${common.domain}
  baseURL: ''
bieService:
  baseURL: ${common.protocol}://species-ws.${common.domain}'
geoserver:
  baseURL: ${common.protocol}://spatial.${common.domain}/geoserver'
biocacheService:
  baseURL: ${common.protocol}://records-ws.${common.domain}'
map:
  minLat: -41.5
  minLng: 114
  maxLat: -13.5
  maxLng: 154
  minimal:
    url: "https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
    attr: "Map data &copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='https://cartodb.com/attributions'>CartoDB</a>"
    subdomains: "abcd"
subgroupFile: '/data/regions/config/regionsGroups.json'
layers:
  enableObjectIntersection: 'false'
  queryContextBieContext: ''
  queryContextOrder: '0'
  queryContextShortName: ''
  queryContextFid: ''
  showQueryContext: 'false'
  intersectObject: ''
  queryContextDisplayName: ''
  queryContextName: ''