---
### OIDC Credentials ###
security:
  jwt:
    clientId: regions
  oidc:
    clientId: regions
    secret: regions-oidc-super-secret
webservice:
  client-id: regions
  client-secret: xxx

grails:
  serverURL: ${common.protocol}://${common.domain}/regions
  cors:
    enabled: false
uriExclusionFilterPattern: /images.*,/css.*,/js.*,/less.*,/vendor.*
breadcrumbParent: ${common.protocol}://${common.domain}/regions/explore-by-location/
alertsResourceName: Atlas
#default:
#  region: Flanders
#  regionType: ''
google:
  apikey: get-a-google-api-key

showNotesInfoInAccordionPanel: 'false'
serverName: ${common.protocol}://${common.domain}/regions
disableCAS: 'false'
uriFilterPattern: /admin/*,/alaAdmin/*
orgNameLong: Vlaams Biodiversiteitsportaal
skin:
  layout: ala-main
  fluidLayout: false
ala:
  skin: ala-main
bie:
  baseURL: ${common.protocol}://${common.domain}/bie-hub
  searchPath: /search
biocache:
  baseURL: ${common.protocol}://${common.domain}/biocache-hub
  enableQueryContext: 'false'
  queryContext: ''
spatial:
  baseURL: ${common.protocol}://${common.domain}/spatial-hub
images:
  baseURL: ${common.protocol}://${common.domain}/image-service
layersService:
  baseURL: ${common.protocol}://${common.domain}/spatial-service
alerts:
  baseURL: ${common.protocol}://${common.domain}/alerts
bieService:
  baseURL: ${common.protocol}://${common.domain}/bie-index
geoserver:
  baseURL: ${common.protocol}://${common.domain}/geoserver
biocacheService:
  baseURL: ${common.protocol}://${common.domain}/biocache-service
map:
  minLat: 49.5294835476
  minLng: 2.51357303225
  maxLat: 51.4750237087
  maxLng: 6.15665815596
  minimal:
    url: "https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
    attr: "Map data &copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a>, imagery &copy; <a href='https://cartodb.com/attributions'>CartoDB</a>"
    subdomains: "abcd"
#subgroupFile: '/data/regions/config/regionsGroups.json'
layers:
  enableObjectIntersection: 'false'
  queryContextBieContext: ''
  queryContextOrder: '0'
  queryContextShortName: ''
  queryContextFid: ''
  showQueryContext: 'false'
  intersectObject: ''
  queryContextDisplayName: ''
  queryContextName: ''