"project_id": "54276" #ala-i18n
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/**/messages.properties",
    "translation": "/%two_letters_code%/%original_file_name%",
  }
]