---
startup:
  baselayers: null
projections: null
---
### OIDC Credentials ###
security:
  jwt:
    clientId: spatial_hub
  oidc:
    clientId: spatial_hub
    secret: spatial_hub-oidc-super-secret
webservice:
  client-id: spatial_hub
  client-secret: xxx

grails:
  serverURL: "${common.protocol}://spatial.${common.domain}"
  app:
    context: "/"
i18n:
  region: 'nl'

viewConfig:
    json: 'view-config.json'

# List of valid user roles.
# Use '*' for ANY role (login will be required).
# Use an empty list for 'login is not required'
user_roles: []


# fq applied to every biocache-service query
qc: ""

#
# spApp configuration
#
spApp:
    # show "map options" and associated controls in the list of layers
    mapOptions: true
    # show map control for collapsing up and hiding the header
    collapseUp: true
    # show map control for collapsing left and hiding left panel
    collapseLeft: true
    # show map control that displays the cursor coordinates (on the lower left of the map, above the scale)
    cursorCoordinates: true
    # show map control that displays the quicklinks
    quicklinks: true
    # show "map options" button "Add WMS Layer"
    optionsAddWms: true
    # show "map options" button "Download Map"
    optionsDownloadMap: false
    # show "map options" button "Reset Map"
    optionsResetMap: true
    # show "map options" section to change the base map
    optionsSelectBaseMap: true
    # load the layerDistances data to display the layer selection list's traffic light indicator
    layerDistances: true
    # show the "add to map | area | google location search" option
    googleLocation: true
    # show the left panel by default
    leftPanel: true
    # show the header by default
    header: true
    # list charts to show on species info page
    charts:
      genus:
        title: "By genus"
        chartType: "doughnut"
        emptyValueMsg: "Genus not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true
      collection_uid:
        title: "By collection"
        chartType: "doughnut"
        emptyValueMsg: "Collection not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true
      assertions:
        title: "By data assertion"
        chartType: "horizontal-bar"
        emptyValueMsg: "Assertion not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true
      type_status:
        title: "By type status (as % of all type specimens)"
        chartType: "doughnut"
        emptyValueMsg: "Type status not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true
      state_conservation:
        title: "By state conservation status"
        chartType: "bar"
        emptyValueMsg: "State conservation not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true
      month:
        title: "By month"
        chartType: "bar"
        emptyValueMsg: "Month not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true
      decade:
        title: "By decade"
        chartType: "bar"
        emptyValueMsg: "Year not specified"
        hideEmptyValues: true
        disableBiocacheQueryOnClick: true

rangeDataTypes:
  - 'tint'
  - 'int'
  - 'tdouble'
  - 'tfloat'
  - 'tdate'
  - 'float'
  - 'double'
  - 'date'

numberOfIntervalsForRangeData: 7
#
# portal.gsp layout options
#
#extraLinkUrl: "https://spatial-old.ala.org.au"
#extraLinkText: "Old site"

date.facet: 'occurrence_date'
date.min: '1780-01-01'
date.max: '2030-01-01'

#
# Override the list of grouped facets from biocache-service (biocacheService.url/search/grouped/facets).
# This is used in a drop down list within the 'Edit species layer' section that is used to  colour or facet
# upon the species layer.
#
#groupedFacets:
#  - title: 'group 1 title'
#    facets:
#      - field: "SOLR field name" (mandatory)
#        sort: 'index' for non-numeric fields OR 'count' or numeric fields (optional, default is index)
#        description: 'label for the field' (optional, default is the SOLR field name)
#        dwcTerm: 'Darwin Core term' (optional)
#        i18nValues: true to translate facet values using biocache-service /facets/i18n OR false (optional, default is false)

#
# Remove fields that are retrieved from biocache-service (biocacheService.url/search/grouped/facets) and
# (biocacheService.url/index/fields)
#
#fieldsIgnored:
#  - field1
#  - field2

#
# Include or Exclude the 'Search facets...' option. This is used in a drop down list within the 'Edit species layer'
# section that is used to colour or facet upon the species layer.
#
facet.search: true

#
# Include or Exclude the grouped facet listing. These grouped facets appear at the end of the drop down list
# within the 'Edit species layer' section that is used to colour or facet upon the species layer.
#
facet.list: true

#
# Enabled multiple species layer filters within the 'Edit species layer' section.
#
filters.enabled: true

#
# Enable workflow header button
#
workflow.enabled: true

#
# List of workflowIds that operate on a species layer. These appear when clicking on the 'default filter' 'filter'
# in the `Edit species layer` section.
#
# These workflows will be forced to operate on the selected layer and should be public.
#
#workflow.speciesFilters: [ { name: 'CSDM default filter', workflowId: 52 } ]
workflow.speciesFilters: []

google:
  apikey: "get-a-google-api-key"

apiKeyCheckUrlTemplate: "${common.protocol}://auth.${common.domain}/apikey/ws/check?apikey={0}"
autocompleteUrl: "${common.protocol}://species-ws.${common.domain}/search/auto.jsonp"

auth:
  admin_role: ROLE_ADMIN

#app:
#  http:
#    header:
#      userId: X-ALA-userId

headerAndFooter:
  baseURL: "${common.protocol}://branding.${common.domain}"
#  version: "2"

ala:
  baseURL: "${common.protocol}://${common.domain}"
bie:
  baseURL: "${common.protocol}://species.${common.domain}"
  searchPath: '/search'

bieService:
  baseURL: "${common.protocol}://species-ws.${common.domain}"

userdetails:
  web:
    url: "${common.protocol}://auth.${common.domain}/userdetails/"
  api:
    url: "${common.protocol}://auth.${common.domain}/userdetails/"

layersService:
  url: "${common.protocol}://spatial.${common.domain}/ws"

lists:
  url: "${common.protocol}://lists.${common.domain}"
  threatenedSpeciesUrl: '/ws/speciesList/?isThreatened=eq:true&isAuthoritative=eq:true'
  invasiveSpeciesUrl: '/ws/speciesList/?isInvasive=eq:true&isAuthoritative=eq:true'
  facets: True
  migratoryDR: dr1005
  iconicSpeciesDR: dr781

journalmap:
  url: "https://www.journalmap.org/"

collections:
  url: "${common.protocol}://collections.${common.domain}"

sandbox:
  url: "${common.protocol}://${common.domain}/sandbox"
  uiUrl: "${common.protocol}://sandbox.${common.domain}/datacheck"

sandboxService:
  url: "${common.protocol}://sandbox.${common.domain}/biocache-service"

gazField: cl2123

userObjectsField: cl1083

biocache:
  url: "${common.protocol}://records.${common.domain}"

biocacheService:
  url: "${common.protocol}://records-ws.${common.domain}"
  #Facets to ignore in the biocache grouped/facets service
  default_facets_ignored: "data_resource_uid,data_provider_uid,species,collection_uid,institution_code_name,institution_uid,uncertainty"
  custom_facets:
    Attribution: [ 'Data Provider;data_provider', 'Collection;collection_name', 'Data Resource;data_resource', 'Institution;institution_name' ]
    Location: [ 'Coordinate Uncertainty;coordinate_uncertainty' ]
    Occurrence: [ 'Year;occurrence_year' ]

sampling:
  url: "${common.protocol}://spatial.${common.domain}/ws"

geoserver:
  url: "${common.protocol}://spatial.${common.domain}/geoserver"

flickr:
  url: "https://api.flickr.com/services/rest/?method="
  searchPhotos: 'flickr.photos.search'
  # licensesInfo: 'flickr.photos.licenses.getInfo'
  # licenses data is found at https://api.flickr.com/services/rest/?method=flickr.photos.licenses.getInfo&api_key=<api_key>&format=json&nojsoncallback=1
  licensesData: { 'licenses': { 'license': [ { 'id': '0', 'name': 'All Rights Reserved', 'url': '' }, { 'id': '4', 'name': 'Attribution License', 'url': 'https://creativecommons.org/licenses/by/2.0/' }, { 'id': '6', 'name': 'Attribution-NoDerivs License', 'url': 'https://creativecommons.org/licenses/by-nd/2.0/' }, { 'id': '3', 'name': 'Attribution-NonCommercial-NoDerivs License', 'url': 'https://creativecommons.org/licenses/by-nc-nd/2.0/' }, { 'id': '2', 'name': 'Attribution-NonCommercial License', 'url': 'https://creativecommons.org/licenses/by-nc/2.0/' }, { 'id': '1', 'name': 'Attribution-NonCommercial-ShareAlike License', 'url': 'https://creativecommons.org/licenses/by-nc-sa/2.0/' }, { 'id': '5', 'name': 'Attribution-ShareAlike License', 'url': 'https://creativecommons.org/licenses/by-sa/2.0/' }, { 'id': '7', 'name': 'No known copyright restrictions', 'url': 'https://www.flickr.com/commons/usage/' }, { 'id': '8', 'name': 'United States Government Work', 'url': 'http://www.usa.gov/copyright.shtml' }, { 'id': '9', 'name': 'Public Domain Dedication (CC0)', 'url': 'https://creativecommons.org/publicdomain/zero/1.0/' }, { 'id': '10', 'name': 'Public Domain Mark', 'url': 'https://creativecommons.org/publicdomain/mark/1.0/' } ] }, 'stat': 'ok' }
  apiKey:
  secret:
  tags:
  extra: "geo,date_taken,owner_name,license,url_t,url_s,url_m,title"
  contentType:
  geoContext:
  filter: "&text=landscape"
  nbrOfPhotosToDisplay: 15

#viewConfig:
#    json: 'view-config.json'

sessions:
  dir: '/data/spatial-hub/sessions'

admin_role: ROLE_ADMIN

skin:
  orgNameLong: "Vlaams Biodiversiteitsportaal"
  orgNameShort: "VBP"
  header: true
  footer: true
  fluidLayout: true
  layout: vlaanderen
#  layout: 'main'

grails.controllers.upload.maxFileSize: 614400000
grails.controllers.upload.maxRequestSize: 614400000

speciesDotSize: 5
speciesDotOpacity: 60

logger:
  baseUrl: "${common.protocol}://logger.${common.domain}/service"

#TBC : decommisioned
phylolink:
  url: "https://phylolink.ala.org.au"

biocollect:
  url: ""

bccvl:
  login:
    url: "https://app.bccvl.org.au/bccvl/oauth2/authorize?client_id=F031d7ce-abb0-11e6-a678-0242ac120005&response_type=token&redirect_uri="
  post:
    url: "https://app.bccvl.org.au/API/dm/v1/import_ala_data"
keep:
  alive:
    timeout:
      ms: 10000

startup:
  lat: 51.0
  lng: 4.4
  zoom: 9
  baselayer:
    default: grb
  baselayers:
#    google_roadmaps:
#      name: 'Streets'
#      layerType: 'ROADMAP'
#      type: 'google'
#      exportType: 'normal'
#      link: 'https://www.google.com/intl/en_au/help/terms_maps.html'
#      projections: ['3857']
#    google_hybrid:
#      name: 'Hybrid'
#      layerType: 'HYBRID'
#      type: 'google'
#      exportType: 'hybrid'
#      link: 'https://www.google.com/intl/en_au/help/terms_maps.html'
#      projections: ['3857']
    grb:
      name: 'Grootschalig Referentiebestand'
      type: 'wms'
      url: "https://geo.api.vlaanderen.be/GRB/wms?"
      layerParams:
        layers: GRB_BSK
        format: 'image/png'
      link: "https://www.vlaanderen.be/datavindplaats/catalogus/wms-grb"
      exportType: 'normal'
    grb_grijs:
      name: 'Grootschalig Referentiebestand (Grijs)'
      type: 'wms'
      url: "https://geo.api.vlaanderen.be/GRB/wms?"
      layerParams:
        layers: GRB_BSK_GRIJS
        format: 'image/png'
      link: "https://www.vlaanderen.be/datavindplaats/catalogus/wms-grb"
      exportType: 'normal'
    luchtkaart:
      name: 'Luchtfoto'
      type: 'wms'
      url: "https://geo.api.vlaanderen.be/OMWRGBMRVL/wms?"
      layerParams:
        layers: OMWRGBMRVL
        format: 'image/png'
      link: "https://www.vlaanderen.be/datavindplaats/catalogus/wms-grb"
      exportType: 'normal'
    osm:
      name: 'Open Street Map'
      url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      type: 'xyz'
      exportType: 'minimal'
      link: 'https://www.openstreetmap.org/about'
      projections: ['3857']
#    google_satellite:
#      name: 'Satellite'
#      layerType: 'SATELLITE'
#      type: 'google'
#      exportType: 'satellite'
#      link: 'https://www.google.com/intl/en_au/help/terms_maps.html'
#      projections: ['3857']

defaultareas:
  - name: 'Flanders'
    fqs: [ 'longitude:[2.296 TO 6.1468505859375]', 'latitude:[50.6 TO 51.5]' ]
    wkt: 'POLYGON((2.296 50.6, 6.1468505859375 50.6, 6.1468505859375 51.5, 2.296 51.5, 2.296 50.6))'
    areaSqKm: 13625
    bbox: [ 50.65843926853822, 51.52780962525605, 2.296, 6.1468505859375 ]
#  - name: 'World'
#    fqs: []
#    wkt: 'POLYGON((-180 -90.0,180.0 -90.0,180.0 90.0,-180 90.0,-180 -90.0))'
#    areaSqKm: 510000000
#    bbox: [-180, -90, 180, 90]

presetWMSServers:
  - name: "GRB"
    url: "https://geo.api.vlaanderen.be/GRB/wms?service=WMS&request=getcapabilities"
  - name: "INBO"
    url: "https://geo.api.vlaanderen.be/INBO/wms?service=WMS&request=getcapabilities"

allowProxy:
  server: "geo.api.vlaanderen.be"

#getMapExamples:
#  - name: "Fractional Cover CLW - Non-PS Veg - 2012.297"
#    url: "http://data.auscover.org.au/geoserver/ows?SERVICE=WMS&REQUEST=GetMap&LAYERS=clw:FractCover.V2_2.NPV&FORMAT=image/png&SRS=epsg:3857&TRANSPARENT=true&VERSION=1.3.0&CRS=EPSG:3857&EXCEPTIONS=INIMAGE&STYLES="

wms:
  intersect: True

fq:
  excludeAbsent: "-occurrence_status_s:absent"

# (mandatory) projections.#.definition - usage new L.Proj.CRS(code, proj4js, params)
# projections.#.definition.code = code
# projections.#.definition.proj4js = proj4js definition (mandatory when not 3857 or 4326)
# projections.#.definition.params = parameters (optional)
#
# (optional) projections.#.origin  (startup lat, lon, zoom is used when origin is not defined)
# projections.#.origin.latitude = default latitude
# projections.#.origin.longitude = default longitude
# projections.#.origin.zoom = default zoom
projection:
  default: 31370
projections:
    3857:
      label: 'Pseudo-Mercator -- Spherical Mercator'
      definition:
        code: 'EPSG:3857' # leaflet supported, uses startup lat,lon,zoom
    31370:
      label: 'Belgische Lambert 1972'
      definition:
        code: 'EPSG:31370'
