---
### OIDC Credentials ###
security:
  jwt:
    clientId: data-quality-filter
  oidc:
    clientId: data-quality-filter
webservice:
  client-id: data-quality-filter
  client-secret: xxx

biocache:
  baseUrl: ${common.protocol}://${common.domain}/biocache-hub
biocacheService:
  baseURL: ${common.protocol}://${common.domain}/biocache-service

server:
  servlet:
    contextPath: /data-quality-filter-service
grails:
  serverURL: ${common.protocol}://${common.domain}/data-quality-filter-service

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

dataSource:
  driverClassName: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect
  url: 'jdbc:postgresql://postgis:5432/dataqualityfilter'
  username: 'dataqualityfilter'
  password: 'my-super-secret-password'
  pooled: true
  jmxExport: true
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

