---
### OIDC Credentials ###
security:
  jwt:
    clientId: ala_hub
  oidc:
    clientId: "ala_bie"
    secret: "ala_bie-oidc-super-secret"
  core:
    optionalFilterPattern: [ "/", "/*" ]
    uriExclusionFilterPattern: ["^/ws/.*"]
webservice:
  client-id: "ala_bie"
  client-secret: "ala_bie-oidc-super-secret"

server:
  servlet:
    contextPath: /bie-hub
grails:
  serverURL: ${common.protocol}://${common.domain}/bie-hub
  cors:
    enabled: true
  cache:
    ehcache:
      ehcacheXmlLocation: 'file:///config/bie-hub/ehcache.xml'

serverName: ${common.protocol}://${common.domain}/bie-hub

userDetails:
  url: ${common.protocol}://${common.domain}/userdetails/

# BIE index webservices
bie:
  baseURL: ${common.protocol}://${common.domain}/bie-hub
  searchPath: /search
  index:
    url: ${common.protocol}://${common.domain}/bie-index

# Query contexts - used to filter search results
bieService:
  baseUrl: ${common.protocol}://${common.domain}/bie-index
  queryContext:
  apiKey: 5bd6d4fc-3f1c-4fa2-903a-7ec771c02999
biocacheService:
  baseURL: ${common.protocol}://${common.domain}/biocache-service
  queryContext: -_nest_parent_:*

ala:
  baseURL: ${common.homepage}
  image:
    service:
      url: ${common.protocol}://${common.domain}/image-service
allowedImageEditingRoles: ROLE_ADMIN,ROLE_EDITOR

wikipedia:
  url: https://nl.wikipedia.org/api/rest_v1/page/html/
  webportalUrl: https://nl.wikipedia.org/wiki/
  lang: nl

# Skin and layout
skin:
  layout: ala

languageCodesUrl: file:///config/bie-hub/languages.json

# Facets displayed on search page
facets: idxtype,rank,locatedInHubCountry,imageAvailable,speciesGroup,taxonomicStatus,conservationStatusAUS_s,conservationStatusACT_s,conservationStatusNSW_s,conservationStatusQLD_s,conservationStatusVIC_s,conservationStatusTAS_s,conservationStatusSA_s,conservationStatusWA_s,conservationStatusNT_s

# Tabs displayed on species page
show:
  tabs: overview,gallery,names,classification,records,literature,sequences,data-partners
  pluginTabs: abv,faunabeheer

# ALA services
biocache:
  baseURL: ${common.protocol}://${common.domain}/biocache-hub

spatial:
  baseURL: ${common.protocol}://${common.domain}/spatial-hub
collectory:
  baseURL: ${common.protocol}://${common.domain}/collectory
  threatenedSpeciesCodesUrl: ${common.protocol}://${common.domain}/collectory/public/showDataResource
collectoryService:
  baseURL: ${common.protocol}://${common.domain}/collectory
speciesList:
  baseURL: ${common.protocol}://${common.domain}/species-list
  preferredSpeciesListDruid: dr152
  preferredListName: Preferred Image List
  apiKey: 081489d3-e581-4dad-8f37-b9331bcf04a8
  wsURL: ${common.protocol}://${common.domain}/species-list
speciesListService:
  baseURL: ${common.protocol}://${common.domain}/species-list
alerts:
  baseUrl: ${common.protocol}://${common.domain}/alerts
regions:
  baseURL: ${common.protocol}://${common.domain}/regions
sightings:
  url:
layersService:
  baseURL: ${common.protocol}://${common.domain}/spatial-service
imageServiceBaseUrl: ${common.protocol}://${common.domain}/image-service

image:
  baseUrl: ${common.protocol}://${common.domain}/image-service
  thumbnailUrl: ${common.protocol}://${common.domain}/image-service/image/

ausTraits:
  baseURL: null
  homeURL: null
  sourceURL: null
  definitionsURL: null

# External Literature and reference sources
synonymsTypes: synonym,homotypicSynonym,objectiveSynonym,heterotypicSynonym,subjectiveSynonym,proParteSynonym,inferredSynonym
literature:
  bhl:
    url: https://biodiversitylibrary.org
    api: https://www.biodiversitylibrary.org/api3
    apikey: get-an-api-key
    fulltext: False
    pageSize: 200
    extend: False
  genbank:
    url: https://www.ncbi.nlm.nih.gov
  scholar:
    url: https://scholar.google.com
  google:
    url: https://www.google.com
  trove:
    url: https://trove.nla.gov.au
    api: https://api.trove.nla.gov.au/v2
    apikey: get-an-api-key
external:
  blacklist: file:///config/bie-hub/blacklist.json

# Mapping options
defaultDecimalLatitude: 51.0
defaultDecimalLongitude: 4.4
defaultZoomLevel: 8
map:
  default:
    url: https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png
    colour: a83d7a
  simpleMapButton: False
  records:
    colour: a83d7a



eol:
  lang: nl
  # Sanitise EOL content
  sanitise: true
  # comma-delimited HTML elements
  html:
    allowedElements: h1,h2,h3,h4,h5,h6,div,a,br,i,b,u,small,strike,span,ul,li,p,sup,cite,ol,em,hr
    # comma-delimited HTML attributes (attribute;pattern;element)
    allowAttributes: href;a;^(http|https|mailto|#).+,class;span,id;span,src;img;^(http|https).+

namematching:
  serviceURL: http://namematching.biodiversiteitsportaal.dev.internal

dataquality:
  enabled: true
  baseUrl: http://data-quality-filter-service.${common.internalDomain}:8080/data-quality-filter-service/

speciesParent: ${common.protocol}://${common.domain}/species-list/iconic-species

supportEmail: ${common.supportEmail}

survey:
  indexPage: False
  searchPage: False
  speciesPage: False
  url:
  header:
  cookieAge: 30
  html:
userdetails:
  url: ${common.protocol}://${common.domain}/userdetails/
  web:
    url: ${common.protocol}://${common.domain}/userdetails/
  api:
    url: ${common.protocol}://${common.domain}/userdetails/
imageFilter: "&qualityProfile=LA"


management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

sortFields: occurrenceCount,score,scientificName,commonNameSingle,rank
defaultSortField: score

environments:
  inbo_dev:
    speciesList:
      preferredSpeciesListDruid: dr384
      preferredListName: Preferred Species Images
    pluginTabsConfig: file:///config/bie-hub/envs/dev/plugin-tabs.json
  inbo_prod:
    speciesList:
      preferredSpeciesListDruid: dr4
      preferredListName: Preferred Image List
    dataquality:
      enabled: false
    pluginTabsConfig: file:///config/bie-hub/envs/prod/plugin-tabs.json