services:
  portal-full:
    image: ${DOCKER_REPO:-local}/inbo-vbp-portal-full:dev
    ports:
      - "1099:1099"
      - "5005:5005"
      - "8181:80"
      - "8080:8080"
    volumes:
      - ../config:/config:ro
      - ../config/biocache-hub:/data/ala-hub/config/ # Hardcoded paths in the biocache-hub
      - ./portal-full/tomcat-manager-ui/host-manager:/usr/local/tomcat/webapps/host-manager
      - ./portal-full/tomcat-manager-ui/manager:/usr/local/tomcat/webapps/manager
      - vbp-data:/data
    environment:
      LOG_LEVEL: "INFO"
      JAVA_OPTS: "-Xmx6g"
      ADDITIONAL_SPRING_CONFIG_LOCATIONS: "file:/config/common/common-docker.yml" # Custom env var used in tomcat context
      SPRING_PROFILES_ACTIVE: "local"
      GRAILS_ENV: local
      REMOTE_DEBUGGER_PORT: 5005
#      REMOTE_JMX_PORT: 1099
#      REMOTE_JMX_PASSWORD: my-super-secret-password
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # Use host, so we can easily swap in port-forwarded version of solr
      - "solr.vbp.internal:host-gateway"
    networks:
      default:
        aliases:
          - alerts.vbp.internal
          - apikey.vbp.internal
          - bie-hub.vbp.internal
          - bie-index.vbp.internal
          - biocache-hub.vbp.internal
          - biocache-service.vbp.internal
          - collectory.vbp.internal
          - doi-service.vbp.internal
          - data-quality-filter-service.vbp.internal
          - image-service.vbp.internal
          - logger.vbp.internal
          - regions.vbp.internal
          - sandbox.vbp.internal
          - spatial-hub.vbp.internal
          - spatial-service.vbp.internal
          - species-list.vbp.internal
          - userdetails.vbp.internal
    depends_on:
      #      solr-init:
      #        condition: service_completed_successfully
      mysql:
        condition: service_healthy
      postgis:
        condition: service_healthy
      mock-oauth2-server:
        condition: service_started

  postgis:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ../config/local-db-init/postgis:/docker-entrypoint-initdb.d
      - postgis:/var/lib/postgresql/data
    #      - ../config/local-db-init/postgis/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_PASSWORD=my-super-secret-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    healthcheck:
      test: pg_isready

  geoserver:
    image: kartoza/geoserver:2.23.2
    networks:
      default:
        aliases:
          - geoserver.vbp.internal
    volumes:
      #geoserver data folder
      # - ./spatial/geoserver/geoserver-files:/data/geoserver-files/
      #Spatials service data folder. If they are both in the same machine, some layers are not needed to be uploaded.
      - vbp-data:/data
    ports:
      - "8079:8080"
    environment:
      JAVA_OPTS: -Xmx1g -Xms128m -Xss256k
      #Geoserver
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
      #If you want to create a user/password
      #NEW_USER: true
      USERNAME: admin
      PASS: my-super-secret-password
      #Geoserver internal server url. It is used to run a local script to init geoserver
      GEOSERVER_URL: http://localhost:8080/geoserver
      GEOSERVER_LOG_PROFILE: PRODUCTION_LOGGING
      GEOSERVER_DATA_DIR: /data/geoserver_data_dir
      GEOWEBCACHE_CACHE_DIR: /data/geoserver_data_dir/gwc
      GEOSERVER_LOG_LOCATION: /data/geoserver_data_dir/logs/geoserver.log
      FOOTPRINTS_DATA_DIR: /data/geoserver_data_dir/footprints_dir
      CONSOLE_HANDLER_LEVEL: INFO
    healthcheck:
      test: curl --fail --head --silent http://localhost:8080

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ../config/local-db-init/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-password
    healthcheck:
      test: mysqladmin ping -h localhost

  mysql-logger-init:
    image: mysql
    volumes:
      - ../config/logger:/config/logger:ro
    command: bash -c "cat /config/logger/db-init/*.sql | mysql --host=mysql --user=logger --password=my-super-secret-password --database logger"
    depends_on:
      mysql:
        condition: service_healthy

  cassandradb:
    image: cassandra:3
    environment:
      HEAP_NEWSIZE: 128M
      MAX_HEAP_SIZE: 2048M
    volumes:
      - cassandra:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]

  cassandra-load-keyspace:
    image: cassandra:3
    environment:
      HEAP_NEWSIZE: 128M
      MAX_HEAP_SIZE: 2048M
    volumes:
      - ../config/local-db-init/cassandra:/docker-entrypoint-initdb.d
    command: bash -c "cqlsh cassandradb -f /docker-entrypoint-initdb.d/*.cql"
    depends_on:
      cassandradb:
        condition: service_healthy

  solr:
    image: solr:8
    networks:
      default:
        aliases:
          - solr.vbp.internal
    ports:
      - "8983:8983"
    volumes:
      - ../config/solr:/var/solr/init/docker/solr-data:ro
      - solr-data:/var/solr/data
    environment:
      SOLR_HEAP: 2g
      SOLR_MODE: solrcloud
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8983/solr/" ]

  solr-init:
    image: solr:8
    entrypoint: [ "bash", "-c" ]
    command:
      - |-
        set -e -x
        ./server/scripts/cloud-scripts/zkcli.sh -zkhost solr:9983 -cmd upconfig -confdir /var/solr/init/docker/solr-data/bie/ -confname bie
        ./server/scripts/cloud-scripts/zkcli.sh -zkhost solr:9983 -cmd clear /configs/bie/managed-schema || true
        
        ./server/scripts/cloud-scripts/zkcli.sh -zkhost solr:9983 -cmd upconfig -confdir /var/solr/init/docker/solr-data/biocache/ -confname biocache
        ./server/scripts/cloud-scripts/zkcli.sh -zkhost solr:9983 -cmd clear /configs/biocache/managed-schema || true

        curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=CREATE&numShards=4&maxShardsPerNode=4&collection.configName=biocache&name=biocache' || curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=RELOAD&name=biocache'
        curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=CREATE&numShards=4&maxShardsPerNode=4&collection.configName=biocache&name=sandbox'  || curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=RELOAD&name=sandbox'
        curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=CREATE&numShards=4&maxShardsPerNode=4&collection.configName=bie&name=bie'           || curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=RELOAD&name=bie'
        curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=CREATE&numShards=4&maxShardsPerNode=4&collection.configName=bie&name=bie-offline'   || curl -X POST --fail 'http://solr:8983/solr/admin/collections?action=RELOAD&name=bie-offline'
    volumes:
      - ../config/solr:/var/solr/init/docker/solr-data:ro
      - solr-data:/var/solr/data
    depends_on:
      solr:
        condition: service_healthy

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    healthcheck:
      test: "wget localhost:8025 --spider -q"

  elasticsearch:
    image: elasticsearch:7.17.20
    domainname: elasticsearch.vbp.internal
    environment:
      ES_JAVA_OPTS: -Xms128m -Xmx1024m
      node.name: elasticsearch
      xpack.security.enabled: false
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://elasticsearch:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5

  namematching:
    image: ${DOCKER_REPO:-local}/inbo-vbp-namematching-service:dev
    networks:
      default:
        aliases:
          - namematching-service.vbp.internal
    command:
      - /config/namematching-service/config.yml
    ports:
      - "9179:9179"
    volumes:
      - ../config/namematching-service:/config/namematching-service:ro

  #  sensitive-data-service:
  #    image: ${DOCKER_REPO:-local}/inbo-vbp-sensitive-data-service:dev
  #    command:
  #      - /config/sensitive-data-service/config.yml
  #    ports:
  #      - "9189:9189"
  #      - "5005:5005"
  #    volumes:
  #      - ../config/sensitive-data-service:/config/sensitive-data-service:ro
  #    environment:
  #      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=*:5005,suspend=n"

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../branding/public:/srv/branding.la-flanders.org/www/
    ports:
      - "80:80"
    healthcheck:
      test: service nginx status || exit 1
    networks:
      default:
        aliases:
          - branding
    depends_on:
      portal-full:
        condition: service_started
      geoserver:
        condition: service_started
      mock-oauth2-server:
        condition: service_started

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.5
    ports:
      - "9999:9999"
    environment:
      SERVER_PORT: 9999
      JSON_CONFIG_PATH: /config/config.json
    volumes:
      - ../config/mock-oauth2-server:/config:ro


networks:
  default:

volumes:
  vbp-data:
  cassandra:
  mysql:
  postgis:
  elasticsearch:
  solr-data:
