allow:
    layer:
        lookup: false
    registry:
        updates: true
auth:
    user:
        details:
            url: http://auth.la-flanders.org/userdetails/userDetails/
        names:
            id:
                path: getUserList
    usernames:
        for:
            numeric:
                id:
                    path: getUserListWithIds
autocomplete:
    commonnames:
        extra:
            enabled: true
    species:
        counts:
            enabled: true
        images:
            enabled: true
biocache:
    ui:
        url: http://records.la-flanders.org
caches:
    auth:
        enabled: false
    collections:
        enabled: false
    layers:
        enabled: false
    log:
        enabled: false
cassandra:
    hosts: cassandradb
    keyspace: occ
    max:
        connections: -1
        retries: 6
    pool: biocache-store-pool
    port: 9042
citations:
    enabled: true
collection:
    contacts:
        url: http://collections.la-flanders.org/ws/collection
concurrent:
    downloads:
        json: '[{"label": "smallSolr", "threads": 4, "maxRecords": 50000, "type":
            "index", "pollDelay": 10, "executionDelay": 10, "threadPriority": 5},
            {"label": "largeSolr", "threads": 1, "maxRecords": 100000000, "type":
            "index", "pollDelay": 100, "executionDelay": 100, "threadPriority": 1},
            {"label": "smallCassandra", "threads": 1, "maxRecords": 50000, "type":
            "db", "pollDelay": 10, "executionDelay": 10, "threadPriority": 5}, {"label":
            "defaultUnrestricted", "threads": 1, "pollDelay": 1000, "executionDelay":
            100, "threadPriority": 1}]}'
db: cassandra
default:
    sample:
        fields: cl20,cl23
deleted:
    file:
        store: /data/biocache-delete/
download:
    batch:
        size: 500
    internal:
        queue:
            size: 1000
    max: 500000
    max.completion.time: 300000
    max.execute.time: 604800000
    throttle:
        ms: 50
    unzipped:
        limit: 10000
dwc:
    url: http://rs.tdwg.org/dwc/terms/
endemic:
    query:
        maxthreads: 30
exclude:
    sensitive:
        values: ''
extra:
    misc:
        fields: ''
facet:
    default: true
facets:
    defaultmax: 0
    max: 4
heatmap:
    output:
        dir: /data/output/heatmap
layers:
    service:
        url: http://spatial.la-flanders.org/ws
list:
    tool:
        url: http://lists.la-flanders.org
media:
    dir: /data/biocache-media/
    url: http://media.la-flanders.org
name:
    index:
        dir: /data/lucene/namematching_v13
namesearch:
    url: http://namematching:9179
qid:
    cache:
        largestCacheableSize: 5242880
        size:
            max: 104857600
            min: 52428800
    wkt:
        maxPoints: 5000
registry:
    url: http://collections.la-flanders.org/ws
sample:
    fields: none
sds:
    url: http://sds.la-flanders.org/sensitive-species-data.xml
service:
    bie:
        enabled: true
        ui:
            url: http://species.la-flanders.org
        ws:
            url: http://species-ws.la-flanders.org/ws
shapefile:
    tmp:
        dir: /data/biocache-download/tmp
solr:
    downloadquery:
        busywaitsleep: 100
        maxthreads: 30
        writertimeout: 60000
    home: http://index.la-flanders.org:8983/solr/biocache
    server:
        indexVersion:
            refresh: 300000
        retry:
            max: 6
            wait: 50
term:
    query:
        limit: 1000
thrift:
    operation:
        timeout: 8000
upload:
    status: /data/biocache-upload/status
    temp: /data/biocache-upload/temp
webservice:
    client-id: ''
    client-secret: ''
    jwt: false
    jwt-scopes: ''
webservices:
    root: http://records-ws.la-flanders.org
wms:
    cache:
        age:
            max: 3600000
        enabled: true
        maxLayerPoints: 100000
        size:
            max: 104857600
            min: 52428800
    facetPivotCutoff: 2000
    highlight:
        radius: 3
    uncertainty:
        max: 30000