---
### OIDC Credentials ###
security:
  jwt:
    clientId: biocache_service
  oidc:
    clientId: "biocache_service"
    secret: "biocache_service-oidc-super-secret"
webservice:
  client-id: "biocache_service"
  client-secret: "biocache_service-oidc-super-secret"

allow:
  layer:
    lookup: false
  registry:
    updates: true
auth:
  user:
    details:
      url: ${common.protocol}://${common.domain}/userdetails/userDetails/
    names:
      id:
        path: getUserList
  usernames:
    for:
      numeric:
        id:
          path: getUserListWithIds
autocomplete:
  commonnames:
    extra:
      enabled: true
  species:
    counts:
      enabled: true
    images:
      enabled: true
    groups:
      url: /config/config/biocache-service/groups.json
    subgroups:
      url: /config/config/biocache-service/subgroups.json
biocache:
  ui:
    url: ${common.protocol}://${common.domain}/biocache-hub
caches:
  auth:
    enabled: false
  collections:
    enabled: false
  layers:
    enabled: false
  log:
    enabled: true
cassandra:
  hosts: cassandradb
  max:
    connections: -1
    retries: 6
  pool: biocache-store-pool
  port: 9042
citations:
  enabled: false
collection:
  contacts:
    url: ${common.protocol}://${common.domain}/collectory/ws/collection
concurrent:
  downloads:
    json: '[{"label": "smallSolr", "threads": 4, "maxRecords": 50000, "type":
            "index", "pollDelay": 10, "executionDelay": 10, "threadPriority": 5},
            {"label": "largeSolr", "threads": 1, "maxRecords": 100000000, "type":
            "index", "pollDelay": 100, "executionDelay": 100, "threadPriority": 1},
            {"label": "smallCassandra", "threads": 1, "maxRecords": 50000, "type":
            "db", "pollDelay": 10, "executionDelay": 10, "threadPriority": 5}, {"label":
            "defaultUnrestricted", "threads": 1, "pollDelay": 1000, "executionDelay":
            100, "threadPriority": 1}]}'
db: cassandra
default:
  sample:
    fields: cl20,cl23
deleted:
  file:
    store: /data/biocache-delete/
download:
  url: ${common.protocol}://${common.domain}/biocache-download
  offline:
    max:
      url: ${common.protocol}://${common.domain}/biocache-download/
  batch:
    size: 500
  internal:
    queue:
      size: 1000
  max: 500000
  max.completion.time: 300000
  max.execute.time: 604800000
  throttle:
    ms: 50
  unzipped:
    limit: 10000
  support:
    email: ${common.supportEmail}
  email:
    subject: "Jouw data op het Vlaams Biodiversiteitsportaal is klaar om te downloaden - [filename]"
    subject.failure: "Er is een fout opgetreden bij het verwerken van jouw downloadverzoek - [filename]"
    body:
      error: "Jouw [hubName] download is mislukt."
    template: /config/config/biocache-service/templates/email.html
  doi:
    resolver: ${common.protocol}://${common.domain}/doi-service
    email:
      template: /config/config/biocache-service/templates/email.html
    title:
      prefix: "Waarnemingen download"
    landing:
        page: ${common.protocol}://${common.domain}/doi-service/
    readme:
      template: /config/config/biocache-service/templates/readme.html
  readme:
    template:
      url: ${common.protocol}://${common.domain}/doi-service/
my:
  download:
    doi:
      baseUrl: ${common.protocol}://${common.domain}/doi-service/myDownloads
dwc:
  url: http://rs.tdwg.org/dwc/terms/
endemic:
  query:
    maxthreads: 30
exclude:
  sensitive:
    values: ''
extra:
  misc:
    fields: ''
facet:
  default: true
  config: /config/config/biocache-service/facets.json
facets:
  defaultmax: 0
  max: 4
heatmap:
  output:
    dir: /data/output/heatmap
layers:
  service:
    url: ${common.protocol}://${common.domain}/spatial-service
list:
  tool:
    url: ${common.protocol}://${common.domain}/species-list
media:
  dir: /data/biocache-media/
  url: ${common.protocol}://${common.domain}/image-service
  store:
    url: ${common.protocol}://${common.domain}/image-service
name:
  index:
    dir: /data/lucene/namematching_v13
namesearch:
  url: http://host.docker.internal:9179
qid:
  cache:
    largestCacheableSize: 5242880
    size:
      max: 104857600
      min: 52428800
  wkt:
    maxPoints: 5000
registry:
  url: ${common.protocol}://${common.domain}/collectory/ws
sample:
  fields: none
sds:
  url: ${common.protocol}://sds.${common.domain}/sensitive-species-data.xml
service:
  bie:
    enabled: true
    ui:
      url: ${common.protocol}://${common.domain}/bie-hub
    ws:
      url: ${common.protocol}://${common.domain}/bie-index/ws
shapefile:
  tmp:
    dir: /data/biocache-download/tmp
solr:
  downloadquery:
    busywaitsleep: 100
    maxthreads: 30
    writertimeout: 60000
  home: http://host.docker.internal:8983/solr/biocache
  server:
    indexVersion:
      refresh: 300000
    retry:
      max: 6
      wait: 50
  pipelines:
    field:
      config: /config/config/biocache-service/pipelines-field-config.json
term:
  query:
    limit: 1000
thrift:
  operation:
    timeout: 8000
upload:
  status: /data/biocache-upload/status
  temp: /data/biocache-upload/temp

webservices:
  root: ${common.protocol}://${common.domain}/biocache-service
  cache-tokens: false

wms:
  cache:
    age:
      max: 3600000
    enabled: true
    maxLayerPoints: 100000
    size:
      max: 104857600
      min: 52428800
  facetPivotCutoff: 2000
  highlight:
    radius: 3
  uncertainty:
    max: 30000

logging:
  config: "file:/config/config/biocache-service/log4j.xml"

cors:
  allowedOrigins: ["*"]

userdetails:
  url: ${common.protocol}://${common.domain}/userdetails
  web:
    url: ${common.protocol}://${common.domain}/userdetails/
  api:
    url: ${common.protocol}://${common.domain}/userdetails/

doi:
  service:
    url: ${common.protocol}://${common.domain}/doi-service/
  provider: VBP


filetype:
  shapefile:
    hidden: true