---
### OIDC Credentials ###
security:
  jwt:
    clientId: sandbox
  oidc:
    clientId: "sandbox"
    secret: "sandbox-oidc-super-secret"
webservice:
  client-id: "sandbox"
  client-secret: "sandbox-oidc-super-secret"


server:
  servlet:
    contextPath: /sandbox

spring:
  application:
    name: sandbox

solr:
  home: http://solr.${common.internalDomain}:8983/solr/sandbox

webservices:
  root: ${common.protocol}://${common.domain}/sandbox

caches:
  auth:
    enabled: false
  collections:
    enabled: false
  layers:
    enabled: false
  log:
    enabled: false