---
### OIDC Credentials ###
security:
  jwt:
    clientId: sandbox
  oidc:
    clientId: "sandbox"
    secret: "sandbox-oidc-super-secret"
webservice:
  client-id: "sandbox"
  client-secret: "sandbox-oidc-super-secret"


server:
  servlet:
    contextPath: /sandbox

spring:
  application:
    name: sandbox

solr:
  home: http://solr.${common.internalDomain}:9983
  collection: sandbox

webservices:
  root: ${common.protocol}://${common.domain}/sandbox

caches:
  auth:
    enabled: false
  collections:
    enabled: false
  layers:
    enabled: false
  log:
    enabled: false

deleted:
  file:
    store: /data/biocache-delete/
download:
  url: ${common.protocol}://${common.domain}/biocache-download
  offline:
    max:
      url: ${common.protocol}://${common.domain}/biocache-download/

shapefile:
  tmp:
    dir: /data/biocache-download/tmp