---
### OIDC Credentials ###
security:
  jwt:
    clientId: sandbox-service
  oidc:
    clientId: "sandbox-service"
    secret: "sandbox-service-oidc-super-secret"
webservice:
  client-id: "sandbox-service"
  client-secret: "sandbox-service-oidc-super-secret"


server:
  servlet:
    contextPath: /sandbox-service

spring:
  application:
    name: sandbox-service

solr:
  home: http://solr.${common.internalDomain}:8983/solr/sandbox
  collection: sandbox

webservices:
  root: ${common.protocol}://${common.domain}/sandbox-service

caches:
  auth:
    enabled: false
  collections:
    enabled: false
  layers:
    enabled: false
  log:
    enabled: false

deleted:
  file:
    store: /data/sandbox-delete/
download:
  url: ${common.protocol}://${common.domain}/sandbox-download
  offline:
    max:
      url: ${common.protocol}://${common.domain}/sandbox-download/

shapefile:
  tmp:
    dir: /data/sandbox-download/tmp