---
### OIDC Credentials ###
security:
  jwt:
    clientId: apikey
  oidc:
    clientId: apikey
    secret: apikey-oidc-super-secret
  core:
    optionalFilterPattern: [ "/", "/*" ]
    uri-exclusion-filter-Pattern: ["^/ws/*"]
management:
  health:
    mongo:
      enabled: false

server:
  servlet:
    contextPath: /apikey
grails:
  serverURL: ${common.protocol}://${common.domain}/apikey

# Data source configuration
dataSource:
  url: jdbc:mysql://apikey:my-super-secret-password@mysql:3306/apikey?serverTimezone=Europe/Brussels&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=False&allowPublicKeyRetrieval=true
flyway:
  baselineOnMigrate: true

ala:
  baseURL: ${common.homepage}

supportEmail: ${common.supportEmail}
homeUrl: ${common.protocol}://${common.domain}
mainTitle: Vlaams Biodiversiteitsportaal
emailSenderTitle: Vlaams Biodiversiteitsportaal
emailSender: ${common.supportEmail}

sightings.url: /mine
spatial.url: ${common.protocol}://${common.domain}/spatial-hub?tool=log
volunteer.url: /user/myStats
lists.url: ${common.protocol}://${common.domain}/species-list/speciesList/list
biocache.search.url: ${common.protocol}://${common.domain}/biocache-hub/occurrences/search
alerts.url: ${common.protocol}://${common.domain}/alerts

# this property is read/used by ala-auth-plugin (included by apikey)
userDetails:
  url: ${common.protocol}://${common.domain}/userdetails/

# Header and footer
ala.baseURL: ${common.homepage}
bie.baseURL: ${common.protocol}://${common.domain}/bie-hub
bie.searchPath: /search

# Skin options
skin:
  layout: ala-main

spring:
  session:
    store-type: none
