{
 "title": "Pipeline Resources",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instanceId",
    "query": {}
   },
   {
    "name": "services",
    "query": "namematching-service, image-service, spatial-service, solr"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "services",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ClusterName": "inbo-vbp-cluster", "ServiceName": "$services" },
     "label": "${PROP('Dim.ServiceName')} - # tasks",
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "$services - resources",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "repeat": "services",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "ClusterName": "inbo-vbp-cluster", "ServiceName": "$services" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "ClusterName": "inbo-vbp-cluster", "ServiceName": "$services" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Average"
    }
   ]
  },
  { "title": "EMR Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Memory $instanceId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "repeat": "instanceId",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceId" },
     "label": "Used",
     "metricName": "mem_used",
     "namespace": "Inbo/VBP",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instanceId" },
     "label": "Available",
     "metricName": "mem_available",
     "namespace": "Inbo/VBP",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Usage $instanceId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 12 },
   "repeat": "instanceId",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceId", "cpu": "cpu-total" },
     "label": "User",
     "metricName": "cpu_usage_user",
     "namespace": "Inbo/VBP",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instanceId", "cpu": "cpu-total" },
     "label": "System",
     "metricName": "cpu_usage_system",
     "namespace": "Inbo/VBP",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instanceId", "cpu": "cpu-total" },
     "label": "IO-Wait",
     "metricName": "cpu_usage_iowait",
     "namespace": "Inbo/VBP",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instanceId", "cpu": "cpu-total" },
     "label": "Idle",
     "metricName": "cpu_usage_idle",
     "namespace": "Inbo/VBP",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network $instanceId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 12 },
   "repeat": "instanceId",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceId" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instanceId" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk $instanceId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "repeat": "instanceId",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "InstanceId": "$instanceId" },
     "metricName": "EBSReadBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "$instanceId" },
     "metricName": "EBSWriteBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}