skin:
  layout: "ala-main"

flyway:
  enabled: true
  table: schema_version

support:
  email: ${common.supportEmail}

server:
  servlet:
    contextPath: /doi-service
grails:
  serverURL: ${common.protocol}://${common.domain}/doi-service

#ands:
#    doi:
#        service:
#            url: https://services.ands.org.au/doi/1.1/
#        app:
#            id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#        key: xxxxxxxxxx
#        client:
#            id: xx
#
#datacite:
#    doi:
#        service:
#            baseApiUrl: https://api.datacite.org/
#            user: XXXXX
#            password: XXXXX
#            fileCacheMaxSizeMb: 64
#            timeOut: 60
#            prefix: 10.XXXXX
#            shoulder: ala


management:
  health:
    elasticsearch:
      enabled: false

ala:
  base:
    url: ${common.protocol}://${common.domain}
  contact:
    form: ${common.protocol}://${common.domain}/contact-todo
doi:
  service:
    mock: true # TODO
    provider:
      #            # define mapping from provider name to a valid DoiProvider (ANDS or DATACITE)
      #      mapping: { ALA: 'DATACITE' }
      mapping: { }

  storage:
    provider: S3
    cloud:
      private: true
  resolverUrl: https://doi.org/
  displayTemplates:
    - "template"
    - "biocache"
    - "phylolink"
    - "csdm"
  publicationLang: "en"
  supportContact: https://${common.domain}/about-the-atlas/communications-centre/
file:
  store: /data/doi-service/files

biocache:
  wsUrl: https://biocache-service.${common.internalDomain}:8080/biocache-service

#dqservice: # TODO
#  url: https://data-quality-service.ala.org.au

elasticSearch:
  plugin:
    mapperAttachment:
      enabled: false
  datastoreImpl: hibernateDatastore
  client:
    mode: transport
    hosts:
      - { host: elasticsearch, port: 9200 }
  cluster.name: elasticsearch
  disableAutoIndex: false
  bulkIndexOnStartup: false

s3:
  temporaryurl:
    duration: 6 # hours

dataSource:
  url: jdbc:postgresql://postgis:5432/doi
  username: doi
  password: my-super-secret-password