skin:
  layout: "ala-main"

flyway:
  enabled: true
  table: schema_version

support:
  email: support@${common.domain}

#ands:
#    doi:
#        service:
#            url: https://services.ands.org.au/doi/1.1/
#        app:
#            id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#        key: xxxxxxxxxx
#        client:
#            id: xx
#
#datacite:
#    doi:
#        service:
#            baseApiUrl: https://api.datacite.org/
#            user: XXXXX
#            password: XXXXX
#            fileCacheMaxSizeMb: 64
#            timeOut: 60
#            prefix: 10.XXXXX
#            shoulder: ala
ala:
  base:
    url: ${common.protocol}://www.${common.domain}
  contact:
    form: ${common.protocol}://www.${common.domain}/contact-todo
doi:
  service:
    mock: true # TODO
    provider:
      #            # define mapping from provider name to a valid DoiProvider (ANDS or DATACITE)
      #      mapping: { ALA: 'DATACITE' }
      mapping: { ALA: 'LOCAL' }

  storage:
    provider: LOCAL
    cloud:
      private: true
  resolverUrl: https://doi.org/
  displayTemplates:
    - "template"
    - "biocache"
    - "phylolink"
    - "csdm"
  publicationLang: "en"
  supportContact: https://www.ala.org.au/about-the-atlas/communications-centre/
file:
  store: /data/doi-service/files

biocache:
  wsUrl: https://records-ws.${common.domain}

#dqservice: # TODO
#  url: https://data-quality-service.ala.org.au

elasticSearch:
  plugin:
    mapperAttachment:
      enabled: false
  datastoreImpl: hibernateDatastore
  client:
    mode: transport
    hosts:
      - { host: localhost, port: 9200 }
  cluster.name: elasticsearch
  disableAutoIndex: false
  bulkIndexOnStartup: false

s3:
  temporaryurl:
    duration: 6 # hours
#
#---
#hibernate:
#    allow_update_outside_transaction: true # Hibernate 5 made transactions required to flush changes, set to true for backwards compat but should be set to false and bugs fixed in the future
#    show_sql: false
#    cache:
#        queries: false
#        use_second_level_cache: false
#        use_query_cache: false
#        region:
#            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
#    dialect: au.org.ala.doi.PostgresqlExtensionsDialect
#
#dataSource:
#    dbCreate: validate
#    pooled: true
#    jmxExport: true
#    driverClassName: org.postgresql.Driver
#    username: root
#    password: password
#    loggingSql: true
#
#environments:
#    development:
#        dataSource:
#            dbCreate: validate
#            url: jdbc:postgresql://localhost/doi
#            username: "postgres"
#            passowrd: "password"
#            logSql: false
#    test:
#        dataSource:
#            dbCreate: validate
#    production:
#        dataSource:
#            dbCreate: validate
#            properties:
#                jmxEnabled: true
#                initialSize: 5
#                maxActive: 50
#                minIdle: 5
#                maxIdle: 25
#                maxWait: 10000
#                maxAge: 600000
#                timeBetweenEvictionRunsMillis: 5000
#                minEvictableIdleTimeMillis: 60000
#                validationQuery: SELECT 1
#                validationQueryTimeout: 3
#                validationInterval: 15000
#                testOnBorrow: true
#                testWhileIdle: true
#                testOnReturn: false
#                jdbcInterceptors: ConnectionState;StatementCache(max=200);SlowQueryReport(logFailed=true)
#                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
#                abandonWhenPercentageFull: 100
#                removeAbandonedTimeout: 120
#                removeAbandoned: true
#                logAbandoned: false