grails:
  serverURL: http://species.la-flanders.org
  cors:
    enabled: true
serverName: http://species.la-flanders.org

# CAS Config
security:
  oidc:
    enabled: true # Cannot disable oidc :(
    discoveryUri: http://auth.la-flanders.org/cas/oidc/.well-known
    scope: openid,profile,email,ala,roles, user_defined
    client-id: "ala_bie"
    secret: "ala_bie-oidc-super-secret"
  jwt:
    enabled: false
    discoveryUri: http://auth.la-flanders.org/cas/oidc/.well-known
    fallbackToLegacyBehaviour: true
  # cognito specific configs
  cas:
    casServerName: http://auth.la-flanders.org
    uriFilterPattern: /admin/*,/alaAdmin/*
    uriExclusionFilterPattern: /images.*,/css.*,/js.*,/less.*
    appServerName: http://species.la-flanders.org
    casServerUrlPrefix: http://auth.la-flanders.org/cas
    loginUrl: http://auth.la-flanders.org/cas/login
    logoutUrl: http://auth.la-flanders.org/cas/logout
    contextPath:
    bypass: false
    applyUriFiltersToTicketValidation: false
    enabled: true
    authCookiename: ALA-Auth
  # cognito specific configs
  apiKey:
    enabled: true
    auth:
      serviceUrl: http://auth.la-flanders.org/apikey/
    check:
      serviceUrl: http://auth.la-flanders.org/apikey/ws/check?apikey=
    userdetails:
      serviceUrl: http://auth.la-flanders.org/userdetails/
webservice:
  jwt: false
  jwt-scopes: test
  client-id: "ala_bie"
  client-secret: "ala_bie-oidc-super-secret"
disableCAS: false
userDetails:
  url: http://auth.la-flanders.org/userdetails/

# BIE index webservices
bie:
  baseURL: http://species.la-flanders.org
  searchPath: /search
  index:
    url: http://species-ws.la-flanders.org

# Query contexts - used to filter search results
bieService:
  baseUrl: http://species-ws.la-flanders.org
  queryContext:
  apiKey: 5bd6d4fc-3f1c-4fa2-903a-7ec771c02999
biocacheService:
  baseURL: http://records-ws.la-flanders.org
  queryContext: -_nest_parent_:*

# Header and footer
headerAndFooter:
  baseURL: http://branding.la-flanders.org
  version: 2

ala:
  baseURL: http://la-flanders.org
  image:
    service:
      url: http://images.la-flanders.org
allowedImageEditingRoles: ROLE_ADMIN,ROLE_EDITOR

wikipedia:
  url: https://en.wikipedia.org/api/rest_v1/page/html/
  lang: en

# Skin and layout
skin:
  homeUrl: http://la-flanders.org
  layout: ala
  orgNameLong: Vlaams Biodiversiteitsportaal
  fluidLayout: true
  orgNameShort: LA Flanders
  favicon: https://raw.githubusercontent.com/living-atlases/artwork/master/favicon.ico

languageCodesUrl: file:///data/ala-bie-hub/config/languages.json

# Facets displayed on search page
facets: idxtype,rank,locatedInHubCountry,imageAvailable,speciesGroup,taxonomicStatus,conservationStatusAUS_s,conservationStatusACT_s,conservationStatusNSW_s,conservationStatusQLD_s,conservationStatusVIC_s,conservationStatusTAS_s,conservationStatusSA_s,conservationStatusWA_s,conservationStatusNT_s

# Tabs displayed on species page
show:
  tabs: overview,gallery,names,classification,records,literature,sequences,data-partners

# ALA services
biocache:
  baseURL: http://records.la-flanders.org

# Other ALA Services
profileService:
  baseURL: https://profiles-ws.ala.org.au/
spatial:
  baseURL: http://spatial.la-flanders.org
collectory:
  baseURL: http://collections.la-flanders.org
  threatenedSpeciesCodesUrl: http://collections.la-flanders.org/public/showDataResource
collectoryService:
  baseURL: http://collections.la-flanders.org/ws
speciesList:
  baseURL: http://lists.la-flanders.org
  preferredSpeciesListDruid: dr4778
  preferredListName: ALA Preferred Species Images
  apiKey: 081489d3-e581-4dad-8f37-b9331bcf04a8
  useListWs: False
  wsURL: http://lists.la-flanders.org/ws
speciesListService:
  baseURL: http://lists.la-flanders.org/ws
alerts:
  baseUrl:
regions:
  baseURL: http://regions.la-flanders.org
sightings:
  url:
layersService:
  baseURL: http://spatial.la-flanders.org/ws
imageServiceBaseURL: http://images.la-flanders.org

image:
  baseUrl: http://images.la-flanders.org
  thumbnailUrl: http://images.la-flanders.org/image/
ausTraits:
  baseURL: http://traitdata.austraits.cloud.edu.au
  homeURL: https://austraits.org/
  sourceURL: https://doi.org/10.5281/zenodo.3568417
  definitionsURL: https://traitecoevo.github.io/austraits.build/articles/trait_definitions.html

# External Literature and reference sources
synonymsTypes: synonym,homotypicSynonym,objectiveSynonym,heterotypicSynonym,subjectiveSynonym,proParteSynonym,inferredSynonym
literature:
  bhl:
    url: https://biodiversitylibrary.org
    api: https://www.biodiversitylibrary.org/api3
    apikey: get-an-api-key
    fulltext: False
    pageSize: 200
    extend: False
  genbank:
    url: https://www.ncbi.nlm.nih.gov
  scholar:
    url: https://scholar.google.com
  google:
    url: https://www.google.com
  trove:
    url: https://trove.nla.gov.au
    api: https://api.trove.nla.gov.au/v2
    apikey: get-an-api-key
external:
  blacklist: file:///data/ala-bie-hub/config/blacklist.json

# Mapping options
defaultDecimalLatitude: 16.942
defaultDecimalLongitude: 1.261
defaultZoomLevel: 4
map:
  default:
    url: https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png
  simpleMapButton: False
  records:
    colour: e6704c



eol:
  lang: en
  # Sanitise EOL content
  sanitise: true
  # comma-delimited HTML elements
  html:
    allowedElements: h1,h2,h3,h4,h5,h6,div,a,br,i,b,u,small,strike,span,ul,li,p,sup,cite,ol,em,hr
    # comma-delimited HTML attributes (attribute;pattern;element)
    allowAttributes: href;a;^(http|https|mailto|#).+,class;span,id;span,src;img;^(http|https).+

namematching:
  serviceURL: https://namematching-ws.ala.org.au

dataquality:
  baseUrl: https://dataquality.ala.org.au/data-profiles

speciesParent: http://lists.la-flanders.org/iconic-species

supportEmail: support@la-flanders.org

survey:
  indexPage: False
  searchPage: False
  speciesPage: False
  url:
  header:
  cookieAge: 30
  html:
userdetails:
  url: http://auth.la-flanders.org/userdetails/
  web:
    url: http://auth.la-flanders.org/userdetails/
  api:
    url: http://auth.la-flanders.org/userdetails/
imageFilter: "&qualityProfile=LA"


management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health