# Custom common config values, used to template others
common:
  protocol: https
  domain: biodiversiteitsportaal.dev.svdev.be
  homepage: ${common.protocol}://${common.domain}
  supportEmail: support.natuurdata@inbo.be

# Common ala config values
ala:
  baseURL: ${common.homepage}

# Header and footer
headerAndFooter:
  baseURL: ${common.protocol}://${common.domain}
  version: 2

# Skin and layout
skin:
  homeUrl: ${common.homepage}
  orgNameLong: Vlaams Biodiversiteitsportaal
  orgNameShort: VBP
  fluidLayout: true
  favicon: '${common.protocol}://${common.domain}/favicon.ico'

# Healthcheck endpoint
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

logging:
  config: /config/config/common/logback.xml

# CORS is managed by cloudfront and nginx
grails:
  cors:
    enabled: false

security:
  cors:
    enable: false

  apikey:
    enabled: true
    auth:
      serviceUrl: ${common.protocol}://${common.domain}/apikey/
    check:
      serviceUrl: ${common.protocol}://${common.domain}/apikey/ws/check?apikey=
    userdetails:
      serviceUrl: ${common.protocol}://${common.domain}/userdetails/
  cas:
    enabled: false
  jwt:
    enabled: true
    discoveryUri: http://mock-oauth2-server:9999/default/.well-known/openid-configuration
    fallbackToLegacyBehaviour: false
  oidc:
    enabled: true
    discoveryUri: http://mock-oauth2-server:9999/default/.well-known/openid-configuration
  core:
    affiliation-survey:
      enabled: false
    authCookieName: VBP-AUTH
    default-logout-redirect-uri: ${common.protocol}://${common.domain}?auth-cookie-action=remove
  cookie:
    enabled: true
    domain: .${common.domain}
webservice:
  jwt: true
  jwt-scopes: openid users/read