environment:
  local:
    common:
      protocol: http
      domain: la-flanders.org
  production:
    common:
      protocol: https
      domain: biodiversiteitsportaal.dev.svdev.be

common:
  protocol: https
  domain: biodiversiteitsportaal.dev.svdev.be
  homepage: ${common.protocol}://www.${common.domain}
ala:
  baseURL: ${common.homepage}

# Header and footer
headerAndFooter:
  baseURL: ${common.protocol}://branding.${common.domain}
  version: 2

# Skin and layout
skin:
  homeUrl: ${common.homepage}
  orgNameLong: Vlaams Biodiversiteitsportaal
  fluidLayout: true
  orgNameShort: VBP

# Healthcheck endpoint
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

logging:
  config: /config/config/common/logback.xml

server:
  use-forward-headers: true


security:
  cors:
    enable: true
    authenticated:
      allowedOriginPatterns: [ "https://.*.${common.domain}" ]
    unauthenticated:
      allowedOriginPatterns: [ "https://.*.${common.domain}" ]
      allowCredentials: false
  apikey:
    enabled: true
    auth:
      serviceUrl: ${common.protocol}://auth.${common.domain}/apikey/
    check:
      serviceUrl: ${common.protocol}://auth.${common.domain}/apikey/ws/check?apikey=
    userdetails:
      serviceUrl: ${common.protocol}://auth.${common.domain}/userdetails/
  cas:
    enabled: false
  jwt:
    enabled: true
    discoveryUri: http://mock-oauth2-server:9999/default/.well-known/openid-configuration
    fallbackToLegacyBehaviour: false
  oidc:
    enabled: true
    discoveryUri: http://mock-oauth2-server:9999/default/.well-known/openid-configuration
  core:
    affiliation-survey:
      enabled: false
    authCookieName: VBP-AUTH
  cookie:
    enabled: true
    domain: .${common.domain}
webservice:
  jwt: true
  jwt-scopes: openid users/read
