common:
  protocol: https
  domain: biodiversiteitsportaal.dev.svdev.be
  homepage: ${common.protocol}://www.${common.domain}

ala:
  baseURL: ${common.homepage}

# Header and footer
headerAndFooter:
  baseURL: ${common.protocol}://branding.${common.domain}
  version: 2

# Skin and layout
skin:
  homeUrl: ${common.homepage}
  orgNameLong: Vlaams Biodiversiteitsportaal
  fluidLayout: true
  orgNameShort: VBP

# Healthcheck endpoint
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

logging:
  config: /config/config/common/logback.xml

server:
  use-forward-headers: true

environment:
  local:
    common:
      protocol: http
      domain: la-flanders.org
  production:
    common:
      protocol: https
      domain: biodiversiteitsportaal.dev.svdev.be

grails:
  cors:
    enabled: true