common:
  protocol: http
  domain: localhost

logging:
  config: /config/config/common/logback-docker.xml

grails:
  cors:
    allowedOriginPatterns: [ "http://localhost" ]

security:
  jwt:
    discoveryUri: http://mock-oauth2-server:9999/default/.well-known/openid-configuration
  oidc:
    discoveryUri: http://mock-oauth2-server:9999/default/.well-known/openid-configuration