common:
  protocol: http
  domain: localhost
  internalDomain: vbp.internal
  homepage: ${common.protocol}://${common.domain}
  supportEmail: support.natuurdata@inbo.be

# Common ala config values
ala:
  baseURL: ${common.homepage}

# Header and footer
headerAndFooter:
  baseURL: ${common.protocol}://${common.domain}
  version: 2

# Skin and layout
skin:
  homeUrl: ${common.homepage}
  orgNameLong: Vlaams Biodiversiteitsportaal
  orgNameShort: VBP
  fluidLayout: true
  favicon: '${common.protocol}://${common.domain}/favicon.ico'

# Actuator configuration
management:
  endpoint:
    health:
      enabled: true
      show-details: never
#    loggers:
#      enabled: true
  endpoints:
#    jmx:
#      domain: org.spring.${appName}
#      exposure:
#        include: loggers
    web:
      exposure:
        include: health


logging:
  config: /config/common/logback.xml

# CORS is managed by cloudfront and nginx
grails:
  cors:
    enabled: false

security:
  cors:
    enable: false

  apikey:
    enabled: true
    header:
      alternatives: "Authorization, X-Authorization"
    auth:
      serviceUrl: ${common.protocol}://${common.domain}/apikey/
    check:
      serviceUrl: ${common.protocol}://${common.domain}/apikey/ws/check?apikey=
    serviceUrl: ${common.protocol}://${common.domain}/apikey/ws/check?apikey=
    userdetails:
      serviceUrl: ${common.protocol}://${common.domain}/userdetails/

  cas:
    enabled: false
  jwt:
    enabled: true
    discoveryUri: http://host.docker.internal:9999/default/.well-known/openid-configuration
    fallbackToLegacyBehaviour: false
  oidc:
    enabled: true
    discoveryUri: http://host.docker.internal:9999/default/.well-known/openid-configuration
    client-authentication-method: client_secret_basic
  core:
    affiliation-survey:
      enabled: false
    authCookieName: VBP-AUTH
    default-logout-redirect-uri: ${common.protocol}://${common.domain}/?logout
  cookie:
    enabled: true
    domain: .${common.domain}
webservice:
  jwt: true
  jwt-scopes: openid users/read

server:
  port: 8080
  tomcat:
    use-relative-redirects: true
  servlet:
    session:
      cookie:
        secure: true
        same-site: "lax" # Strict causes pac4j issues

environments:
  local:
    common:
      protocol: http
      domain: localhost
  inbo_dev:
    common:
      protocol: https
      domain: natuurdata.dev.inbo.be
  inbo_uat:
    common:
      protocol: https
      domain: natuurdata.uat.inbo.be
  inbo_prod:
    common:
      protocol: https
      domain: natuurdata.inbo.be