# Custom common config values, used to template others
common:
  protocol: https
  domain: biodiversiteitsportaal.dev.svdev.be
  homepage: ${common.protocol}://www.${common.domain}
  supportEmail: support.natuurdata@inbo.be
