common:
  protocol: http
  domain: biodiversiteitsportaal.dev.inbo.be
  baseUrl: ${common.protocol}://${common.domain}

ala:
  baseURL: ${common.baseUrl}

# Header and footer
headerAndFooter:
  baseURL: ${common.baseUrl}
  version: 2

# Skin and layout
skin:
  homeUrl: ${common.baseUrl}
  orgNameLong: Vlaams Biodiversiteitsportaal
  fluidLayout: true
  orgNameShort: VlBiDiP

# Healthcheck endpoint
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

environments:
    production:
      logging:
        config: /config/config/common/logback-colorized-terminal.xml
#        config: /config/common/logback-json.xml