otel.javaagent.logging=application
otel.propagators=xray,tracecontext
otel.traces.sampler=parentbased_traceidratio
otel.traces.sampler.arg=0.05
otel_metrics_exporter=none
otel.exporter.otlp.endpoint=http://localhost:4317
otel.logs.exporter=none
otel.instrumentation.grails.enabled=false
otel.instrumentation.experimental.span-suppression-strategy=semconv
otel.instrumentation.http.client.emit-experimental-telemetry=true

# Messes up figuring out the service name, disabling restriction for now
# otel.java.enabled.resource.providers=io.opentelemetry.sdk.autoconfigure.internal.EnvironmentResourceProvider,io.opentelemetry.contrib.aws.resource.EcsResourceProvider
