---
# mail.enabled: true will send email via a mail server depending on the mail.ses.enabled

# Set mail.ses.enabled true will use AWS SES, it requires the AWS credentials to be set in the environment variables
# Set false will use the default grails mail plugin, we need to config the mail server and port in grails.mail
# In dev, email will be posted to Postie docker container, which can be accessed via http://localhost:3000

mail:
  enabled: true
  ses:
    enabled: false
  details:
    sender: "${common.supportEmail}"
    alertAddressTitle: "Atlas alerts"
    infoSender: "${common.supportEmail}"
    infoAddressTitle: "Atlas of Living Australia"
    defaultResourceName: "Atlas of Living Australia"
    # forceAllAlertsGetSent results in emails getting sent regardless if data has changed - only use in DEV env
    forceAllAlertsGetSent: false

grails:
  #default mail service
  serverURL: "${common.protocol}://${common.domain}/alerts"
  mail:
    port: 25
    server: mailhog

  plugin:
    awssdk:
      region: eu-west-1
      s3:
        bucket: ala-alerts-test
        region: eu-west-1

security:
skin:
  layout: "ala-main"
  orgSupportEmail: ${common.supportEmail}
privacyPolicy: "${common.protocol}://${common.domain}/terms-of-use/privacy-policy/"
siteDefaultLanguage: "nl"

ala:
  baseURL: "${common.protocol}://${common.domain}"
  userDetailsURL: "${common.protocol}://${common.domain}/userdetails/userDetails/getUserListFull"
biocacheService:
  baseURL: "${common.protocol}://${common.domain}/biocache-service"
biocache:
  baseURL: "${common.protocol}://${common.domain}/biocache-hub"
spatial:
  baseURL: "${common.protocol}://${common.domain}/spatial-hub"
collectory:
  baseURL: "${common.protocol}://${common.domain}/collectory"
lists:
  baseURL: "${common.protocol}://${common.domain}/species-list"
speciesPages:
  searchURL: "${common.protocol}://${common.domain}/bie-hub/species/Tiliqua+rugosa"
  searchTitle: Shingle-back
collection:
  searchURL: "${common.protocol}://${common.domain}/collectory/public/show/co13"
  searchTitle: ANIC
regions:
  searchURL: "${common.protocol}://${common.domain}/regions/states/Australian+Capital+Territory"
  searchTitle: ACT
occurrence:
  searchURL: "${common.protocol}://${common.domain}/biocache-hub/occurrences/search?q=passer"
  searchTitle: occurrence search
userdetails:
  web:
    url: "${common.protocol}://${common.domain}/userdetails/"

useSpeciesListsAlerts: true
useSpatialAlerts: true
useBlogsAlerts: true
useCitizenScienceAlerts: true
biosecurity:
  cronExpression: '0 30 9 ? * WED'
  query:
    template:
      authoritativeList: /occurrences/search?q=species_list_uid:___LISTIDPARAM___&fq=decade:2020&fq=country:Australia&fq=first_loaded_date:[___DATEPARAM___%20TO%20*]&fq=occurrence_date:[___LASTYEARPARAM___%20TO%20*]&sort=first_loaded_date&dir=desc&disableAllQualityFilters=true
      nonAuthoritativeList: /occurrences/search?q=species_list:___LISTIDPARAM___&fq=decade:2020&fq=country:Australia&fq=first_loaded_date:[___DATEPARAM___%20TO%20*]&fq=occurrence_date:[___LASTYEARPARAM___%20TO%20*]&sort=first_loaded_date&dir=desc&disableAllQualityFilters=true
    maxRecords: 500
  moreinfo:
    link: ${common.protocol}://${common.domain}/blogs-news/ala-helps-to-stop-pests-in-their-tracks/
  csv:
    local:
      enabled: true
      directory: /data/alerts/csv
    s3:
      enabled: false
      bucket: alerts
    # read lga from the layer
    lga: LGA2023

  legacy:
    aus: cl927:*
    act: cl927:"Australian Capital Territory" OR cl927:"Jervis Bay Territory"
    sa: cl927:"South Australia (including Coastal Waters)"
    vic: cl927:"Victoria (including Coastal Waters)"
    wa: cl927:"Western Australia (including Coastal Waters)"
    nt: cl927:"Northern Territory (including Coastal Waters)"
    qld: cl927:"Queensland (including Coastal Waters)"
    tas: cl927:"Tasmania (including Coastal Waters)"
    nsw: cl927:"New South Wales (including Coastal Waters)"
    lgaField: cl10923
    shape: cl11033:"Namadgi" OR cl11033:"Tidbinbilla" OR cl11033:"Bimberi"
    #shape: spatialObject:9223660
    eventDateAge: 150
    firstLoadedDateAge: 8

dataSource:
  url: jdbc:mysql://alerts:my-super-secret-password@mysql/alerts
