logging:
  level: INFO
  loggers:
    au.org.ala: WARN
    org.reflections: ERROR
  appenders:
    - type: console
      target: stdout
      logFormat: "%date{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%level]) %cyan([%logger{10} %file:%line]) %replace([%X{AWS-XRAY-TRACE-ID}]){'\\[\\]', ''}%msg%n"
server:
#  rootPath: '/namematching-service/*'
  applicationConnectors:
    - type: http
      port: 9179
      outputBufferSize: 32KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
  adminConnectors:
    - type: http
      port: 9180
search:
  index: /data/lucene/namematching-nm
