logging:
  level: INFO
  loggers:
    au.org.ala: WARN
    org.reflections: ERROR
  appenders:
    - type: console
      target: stdout
      logFormat: "%date{ISO8601} %highlight([%level]) %cyan([%logger{10}]) %msg%replace( [t=%X{trace_id},s=%X{span_id}]){' \\[t=,s=\\]',''}%n"

server:
#  rootPath: '/namematching-service/*'
  requestLog:
    appenders:
      - type: console
        filterFactories:
          - type: uri
            uris:
              - "/"
  applicationConnectors:
    - type: http
      port: 9179
      outputBufferSize: 32KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
  adminConnectors:
    - type: http
      port: 9180
search:
  index: /data/lucene/namematching-nm