{
 "title": "Portal Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "loadbalancer",
    "query": {}
   },
   { "name": "responseCode", "query": "2XX,3XX,4XX,5XX" }
  ]
 },
 "panels": [
  {
   "title": "# Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/inbo-vbp-public/a744d69ec78da33a",
      "TargetGroup": "*"
     },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "RequestCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(RequestCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancer'",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "expression": "SELECT SUM(RequestCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/inbo-vbp-public/a744d69ec78da33a'\n",
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_ELB_4XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "$elb_targets" }, "property": { "name": "TargetGroup", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_ELB_4XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancer' AND TargetGroup = '$elb_targets'",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "expression": "SELECT SUM(RequestCount) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/inbo-vbp-public/a744d69ec78da33a'\n",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$loadbalancer" }, "property": { "name": "LoadBalancer", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "$elb_targets" }, "property": { "name": "TargetGroup", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = '$loadbalancer' AND TargetGroup = '$elb_targets'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Application ELB requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Errors and warnings",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, @logStream |\n filter @logStream like /$service\\/.*/ |\n filter @message like /\\[(?:ERROR|WARN)\\]/ |\n sort @timestamp desc |\n limit 100",
     "logGroups": [
      { "arn": "/inbo/vbp/ecs", "name": "/inbo/vbp/ecs" },
      { "arn": "/inbo/vbp/lambda", "name": "/inbo/vbp/lambda" },
      { "arn": "/inbo/vbp/pipelines", "name": "/inbo/vbp/pipelines" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Fault traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "group": {
      "GroupARN": "arn:aws:xray:eu-west-1:632683202044:group/Default",
      "GroupName": "Default",
      "InsightsConfiguration": {
       "InsightsEnabled": false,
       "NotificationsEnabled": false
      }
     },
     "query": "fault",
     "queryMode": "X-Ray",
     "region": "default"
    }
   ]
  },
  {
   "title": "ELB Target health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "*" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Running tasks",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dimensions": { "ClusterName": "$cluster", "ServiceName": "*" },
     "metricName": "RunningTaskCount",
     "namespace": "ECS/ContainerInsights",
     "period": "$__interval",
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Average"
    }
   ]
  }
 ]
}