---
### OIDC Credentials ###
security:
  jwt:
    clientId: lists
  oidc:
    clientId: lists
    secret: lists-oidc-super-secret
webservice:
  client-id: lists
  client-secret: xxx


apiGateway:
  enabled: false
auth:
  userDetailsUrl: ${common.protocol}://${common.domain}/userdetails/userDetails/
batchSize: 500
bie:
  baseURL: ${common.protocol}://${common.domain}/bie-hub
  download: /data/bie-staging/species-list
  nameIndexLocation: /data/lucene/namematching
  searchPath: /search
bieService:
  baseURL: ${common.protocol}://${common.domain}/bie-index
biocache:
  baseURL: ${common.protocol}://${common.domain}/biocache-hub
biocacheService:
  baseURL: ${common.protocol}://${common.domain}/biocache-service
collectory:
  baseURL: ${common.protocol}://${common.domain}/collectory
  enableSync: true
dataSource:
  url: jdbc:mysql://species:my-super-secret-password@mysql:3306/specieslists?allowPublicKeyRetrieval=true&autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8&useSSL=False
  properties:
    initialSize: 2
    maxActive: 20
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
downloadLimit: 200
fieldGuide:
  baseURL: ''

server:
  servlet:
    contextPath: /species-list
grails:
  serverURL: ${common.protocol}://${common.domain}/species-list
  cache:
    ehcache:
      ehcacheXmlLocation: 'file:///config/species-list/ehcache.xml'

iconicSpecies:
  uid: dr781
logger:
  baseURL: ${common.protocol}://${common.domain}/logger/service
  baseUrl: ${common.protocol}://${common.domain}/logger/service
namematching:
  serviceURL: http://namematching:9179
openapi:
  components:
    security:
      oauth2:
        baseUrl: ${common.protocol}://auth.${common.domain}/cas/oidc
  contact:
    email: ${common.supportEmail}
  terms: ''
outboundhttp:
  timeout: 8000
ownerVisibleToEditor: false
publicview:
  hidePrivateLists: true

maxItemsPerPage: 25

serverName: ${common.protocol}://${common.domain}/species-list
serverURL: ${common.protocol}://${common.domain}/species-list
skin:
  layout: ala-main
spatial:
  baseURL: ${common.protocol}://${common.domain}/spatial-hub
termsOfUseUrl: ''
userdetails:
  api:
    url: ${common.protocol}://${common.domain}/userdetails/
  web:
    url: ${common.protocol}://${common.domain}/userdetails/

hibernate:
  jdbc:
    batch_size: 500
  order_inserts: true
  order_updates: true
  generate_statistics: true
