ala:
    baseURL: http://la-flanders.org
apiGateway:
    enabled: false
auth:
    userDetailsUrl: http://auth.la-flanders.org/userdetails/userDetails/
batchSize: 500
bie:
    baseURL: http://species.la-flanders.org
    download: /data/bie-staging/species-list
    nameIndexLocation: /data/lucene/namematching
    searchPath: /search
bieService:
    baseURL: http://species-ws.la-flanders.org
biocache:
    baseURL: http://records.la-flanders.org
biocacheService:
    baseURL: http://records-ws.la-flanders.org
collectory:
    baseURL: http://collections.la-flanders.org
    enableSync: false
dataSource:
    dbCreate: update
    driverClassName: com.mysql.jdbc.Driver
    password: my-super-secret-password
    url: jdbc:mysql://mysql:3306/specieslists?allowPublicKeyRetrieval=true&autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8&useSSL=False
    username: species
downloadLimit: 200
fieldGuide:
    baseURL: ''
grails:
    serverURL: http://lists.la-flanders.org
headerAndFooter:
    baseURL: http://branding.la-flanders.org
    version: 2
httpTimeoutMillis: 60000
iconicSpecies:
    uid: dr781
logger:
    baseURL: http://logger.la-flanders.org/service
    baseUrl: http://logger.la-flanders.org/service
management:
    endpoint:
        health:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health
namematching:
    serviceURL: https://namematching-ws.ala.org.au
openapi:
    components:
        security:
            oauth2:
                baseUrl: http://auth.la-flanders.org/cas/oidc
    contact:
        email: support@la-flanders.org
    terms: ''
outboundhttp:
    timeout: 8000
ownerVisibleToEditor: false
publicview:
    hidePrivateLists: true
registryApiKey: 449cac3c-0498-4c25-ae0b-2517267c3f05
security:
    apikey:
        auth:
            serviceUrl: http://auth.la-flanders.org/apikey/ws/check/
        check:
            serviceUrl: http://auth.la-flanders.org/apikey/ws/check?apikey=
        enabled: true
        header:
            alternatives: Authorization
        userdetails:
            serviceUrl: http://auth.la-flanders.org/userdetails/userDetails/
    cas:
        appServerName: http://lists.la-flanders.org
        authCookieName: ALA-Auth
        bypass: false
        casServerName: http://auth.la-flanders.org
        casServerUrlPrefix: http://auth.la-flanders.org/cas/
        contextPath: ''
        enabled: true
        loginUrl: http://auth.la-flanders.org/cas/login
        logoutUrl: http://auth.la-flanders.org/cas/logout
    cookie:
        domain: .la-flanders.org
        enabled: false
    core:
        authCookieName: ALA-Auth
    jwt:
        clientId: lists
        discoveryUri: http://auth.la-flanders.org/cas/oidc/.well-known
        enabled: true
        fallbackToLegacyBehaviour: true
        roleAttributes: cognito:groups
    oidc:
        clientId: lists
        discoveryUri: http://auth.la-flanders.org/cas/oidc/.well-known
        enabled: false
        secret: lists-oidc-super-secret
serverName: http://lists.la-flanders.org
serverURL: http://lists.la-flanders.org
skin:
    favicon: https://raw.githubusercontent.com/living-atlases/artwork/master/favicon.ico
    fluidLayout: true
    homeUrl: http://la-flanders.org
    layout: main
    orgNameLong: Vlaams Biodiversiteitsportaal
    orgNameShort: LA Flanders
spatial:
    baseURL: http://spatial.la-flanders.org
termsOfUseUrl: ''
userdetails:
    api:
        url: http://auth.la-flanders.org/userdetails/
    web:
        url: http://auth.la-flanders.org/userdetails/
webservice:
    client-id: ''
    client-secret: ''
    jwt: false
    jwt-scopes: ''