---
### OIDC Credentials ###
security:
  jwt:
    clientId: collections
  oidc:
    clientId: collections
  core:
    optionalFilterPattern: [ "/", "/*" ]
    uriExclusionFilterPattern: ["^/ws/.*"]
webservice:
  client-id: collections
  client-secret: xxx

ROLE_ADMIN: ROLE_ADMIN
ROLE_EDITOR: ROLE_EDITOR
ala:
  baseURL: ${common.homepage}
alertUrl: ""
alertsUrl: ""
bie:
  baseURL: ${common.protocol}://${common.domain}/bie-hub
  searchPath: /search
biocacheServicesUrl: ${common.protocol}://${common.domain}/biocache-service
biocacheUiURL: ${common.protocol}://${common.domain}/biocache-hub
citation:
  link:
    template: "For more information: @link@"
  rights:
    template: ""
  template: Records provided by @entityName@, accessed through ALA website.
collectionsMap:
  centreMapLat: 51.0
  centreMapLon: 4.4
  defaultZoom: 9
dataSource:
  url: jdbc:mysql://collectory:my-super-secret-password@mysql:3306/collectory?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=False&serverTimezone=Europe/Paris
  pooled: true
  jmxExport: true
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

defaultLocale: en
disableAlertLinks: true
disableCAS: false
disableLoggerLinks: false
disableOverviewMap: false
eml:
  administrativeArea: ACT
  city: Camberra
  country: Australia
  deliveryPoint: Clunies Ross Street
  electronicMailAddress: ${common.supportEmail}
  organizationName: Vlaams Biodiversiteitsportaal
  postalCode: 2601
gbifApiPassword: ""
gbifApiUrl: https://api.gbif.org/v1/
gbifApiUser: ""
gbifDefaultEntityCountry: BEL
gbifEndorsingNodeKey: ""
gbifExportUrlBase: ""
gbifInstallationKey: ""
gbifLicenceMappingUrl: file:///config/collectory/default-gbif-license-mapping.json
gbifOrphansPublisherID: ""
gbifRegistrationDryRun: true
gbifRegistrationEnabled: false
gbifWebsite: https://www.gbif.org
google:
  apikey: get-a-google-api-key

server:
  servlet:
    contextPath: /collectory
grails:
  controllers:
    upload:
      maxFileSize: 107374182400
      maxRequestSize: 107374182400
  cors:
    enabled: true
  resources:
    adhoc:
      patterns:
        "['/images/*', '/data/*', '/img/*', '/theme/default/*', '/css/*',
                '/js/*', '/plugins/*' ]"
  serverURL: ${common.protocol}://${common.domain}/collectory
isPipelinesCompatible: false
loggerURL: ${common.protocol}://${common.domain}/logger/service
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
mapboxAccessToken: RequestAMapBoxKey
openapi:
  components:
    security:
      oauth2:
        baseUrl: ${common.protocol}://auth.${common.domain}/cas/oidc
  contact:
    email: ${common.supportEmail}
  terms: ""
orgNameLong: Vlaams Biodiversiteitsportaal
projectName: Vlaams Biodiversiteitsportaal
projectNameShort: VBP
regionName: België en Vlaanderen
repository:
  location:
    images: /data/collectory/data
resource:
  gbifExport:
    url:
      template: ${common.protocol}://${common.domain}/biocache-hub/archives/gbif/@UID@/@UID@.zip
  publicArchive:
    url:
      template: ${common.protocol}://${common.domain}/biocache-hub/archives/gbif/@UID@/@UID@.zip
rifcs:
  excludeBounds: true
serverName: ${common.protocol}://${common.domain}/collectory


showExtraInfoInDataSetsView:
  enabled: "true "
  relativeTime: true
skin:
  taxaLinks:
    baseUrl: ${common.protocol}://${common.domain}/bie-hub/species/
spatial:
  baseURL: ${common.protocol}://${common.domain}/spatial-hub
speciesListToolUrl: ${common.protocol}://${common.domain}/species-list/speciesListItem/list/
suitableFor: '[{"spListNational":"Species list national"}, {"spListState":
    "Species list state"}, {"spListGreaterThan1000": "Species list >1000km
    radius"}, {"spList100to1000": "Species list 100-1000km radius"},
    {"spList10to100":"Species list 10k to 100km radius"},
    {"spListLessThan10":"Species list <10km radius"},
    {"speciesDistribution":"Defining a species distribution"},
    {"quantifyAbundance":"Quantifying abundance at a point in time"},
    {"quantifyChange": "Quantifying change over time"}, {"other":"Other"}]'
uploadExternalUrlPath: /upload/
uploadFilePath: /data/collectory/upload/
useGbifDoi: false
userDetails:
  url: ${common.protocol}://${common.domain}/userdetails/
userdetails:
  api:
    url: ${common.protocol}://${common.domain}/userdetails/
  url: ${common.protocol}://${common.domain}/userdetails/
  web:
    url: ${common.protocol}://${common.domain}/userdetails/

dataResource:
  resourceTypeList:
    - records
    - website
    - document
    - uploads
    - species-list
    - publications
    - events
  contentTypesList:
    - authoritative
    - behaviour
    - citizen science
    - commercial uses
    - common names
    - conservation management
    - conservation status
    - description
    - distribution maps
    - distribution text
    - Barcoding DNA
    - Genomic DNA
    - Environmental DNA
    - feeding and diet
    - habitat
    - human interaction
    - identification keys
    - images
    - lifecycle
    - molecular
    - movies
    - pest management
    - pest status
    - point occurrence data
    - population
    - references
    - reproduction
    - scientific names
    - sensitive species lists
    - similar species
    - sound
    - species interactions
    - species list
    - taxonomy
    - threats
