---
### OIDC Credentials ###
security:
  jwt:
    clientId: logger
  oidc:
    clientId: logger
    secret: logger-oidc-super-secret
webservice:
  client-id: logger
  client-secret: xxx

server:
  servlet:
    contextPath: /logger
grails:
  serverURL: ${common.protocol}://logger.${common.domain}

dataSource:
  url: jdbc:mysql://logger:my-super-secret-password@mysql:3306/logger?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=False&serverTimezone=Europe/Paris