---
name: Scheduled E2E tests against the VBP portal
run-name: Scheduled test of the VBP portal on DEV

on:
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  test-dev:
    uses: ./.github/workflows/e2e-test.yml
    with:
      env: 'dev'
      google_notification: true
  test-prod:
    uses: ./.github/workflows/e2e-test.yml
    with:
      env: 'prod'
      google_notification: true