name: Run E2E tests against the VBP portal
run-name: ${{ github.actor }} is testing the VBP portal @ ${{ github.event.inputs.host }}

on:
  schedule:
    - cron: '0 5 * * 1-5'
  workflow_dispatch:
    inputs:
      host:
        description: 'Host endpoint to test'
        required: true
        default: 'https://natuurdata.inbo.be'
        type: choice
        options:
          - 'https://natuurdata.dev.inbo.be'
          - 'https://natuurdata.uat.inbo.be'
          - 'https://natuurdata.inbo.be'
jobs:
  e2e-test:
    runs-on: [ self-hosted ]
    container:
      image: cypress/browsers:22.15.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_VBP_USERNAME: ${{ secrets.CYPRESS_VBP_USERNAME }}
          CYPRESS_VBP_PASSWORD: ${{ secrets.CYPRESS_VBP_PASSWORD }}
        with:
          working-directory: ./test
          config: baseUrl=${{ github.event.inputs.host }}

      - uses: actions/upload-artifact@v4
        id: upload-screen-captures
        if: failure()
        with:
          name: upload-screen-captures
          path: |
            ./test/cypress/screenshots
            ./test/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
          retention-days: 5

      - name: Notify Google Chat
        if: failure()
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        run: |
          cat > google-chat.json <<EOF
          {
            "cardsV2": [
              {
                "card": {
                  "header": {
                    "title": "Automated Regression Test Failed",
                    "imageUrl": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.3TogH2tQvYaU5cv4-EEcvwHaHa%26pid%3DApi&f=1&ipt=39902d7c82156c8499eb40496594a16b7a1d97c47c7a284eb7d95465e04b0251",
                    "imageType": "SQUARE"
                  },
                  "sections": [
                    {
                      "collapsible": false,
                      "widgets": [
                        {
                          "buttonList": {
                            "buttons": [
                              {
                                "text": "Go to test run",
                                "type": "FILLED",
                                "icon": {
                                  "materialIcon": {
                                    "name": "checklist"
                                  }
                                },
                                "onClick": {
                                  "openLink": {
                                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                                  }
                                }
                              },
                              {
                                "text": "Download Screen Captures",
                                "type": "FILLED_TONAL",
                                "icon": {
                                  "materialIcon": {
                                    "name": "photo_frame"
                                  }
                                },
                                "onClick": {
                                  "openLink": {
                                    "url": "${{ steps.upload-screen-captures.outputs.artifact-url }}"
                                  }
                                }
                              }
                            ]
                          }
                        }
                      ]
                    },
                    {
                      "collapsible": true,
                      "collapseControl": {
                        "horizontalAlignment": "CENTER",
                        "collapseButton": {
                          "icon": {
                            "materialIcon": {
                              "name": "attachment"
                            }
                          },
                          "text": "Hide results",
                          "type": "BORDERLESS"
                        },
                        "expandButton": {
                          "icon": {
                            "materialIcon": {
                              "name": "attachment"
                            }
                          },
                          "text": "Show results",
                          "type": "BORDERLESS"
                        }
                      },
                      "uncollapsibleWidgetsCount": 1,
                      "widgets": [
                        {
                          "decoratedText": {
                            "text": "$(cat ./google-chat-report.md)"
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }
          EOF

          wget \
          --header="Content-Type: application/json" \
          --post-file=./google-chat.json \
          "$GOOGLE_CHAT_WEBHOOK_URL"