name: Run E2E tests against the VBP portal
run-name: ${{ github.actor }} is testing the VBP portal @ ${{ github.event.inputs.host }}

on:
  cron: '0 5 * * 1-5'
  workflow_dispatch:
    inputs:
      host:
        description: 'Host endpoint to test'
        required: true
        default: 'https://natuurdata.inbo.be'
        type: choice
        options:
        - 'https://natuurdata.dev.inbo.be'
        - 'https://natuurdata.uat.inbo.be'
        - 'https://natuurdata.inbo.be'
jobs:
  e2e-test:
    runs-on: [ self-hosted ]
    container:
      image: cypress/browsers:22.15.0
      options: --user 1001
    steps:
      - uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_VBP_USERNAME: ${{ secrets.CYPRESS_VBP_USERNAME }}
          CYPRESS_VBP_PASSWORD: ${{ secrets.CYPRESS_VBP_PASSWORD }}
        with:
          working-directory: ./test
          config: baseUrl=${{ github.event.inputs.host }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ./test/cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
          retention-days: 5
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: ./test/cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
          retention-days: 5

      - name: Notify Google Chat
        if: failure()
        uses: SimonScholz/google-chat-action@v1.1.0
        with:
          webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
          createDefaultSection: false
          collapsibleDefaultSection: false
          title: e2e tests failed @ ${{ github.event.inputs.host }}
          subtitle: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
