name: Release new version of the portal
run-name: ${{ github.actor }} is releasing a new version
on:
  push:
    branches:
      - 'main'
      - 'dev'
jobs:
#  cleanup:
#    runs-on: [ stefan ]
#    container:
#      image: bitnami/git
#      volumes:
#        - /home/github-runner:/runner/_work/vlaams-biodiversiteitsportaal/
#    steps:
#      - name: cleanup
#        id: output
#        run: |
#          rm -rf -v ./*
#          rm -rf -v ./.git
#          rm -rf -v /home/github-runner/_work/vlaams-biodiversiteitsportaal/
#          rm -rf -v /runner/_work/vlaams-biodiversiteitsportaal/

  get-versions:
    runs-on: [ stefan ]
#    needs: cleanup
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all component versions
        id: versions
        env:
          COMPONENTS: "alerts apikey"
        run: |
          # Branding
          COMPONENT=branding
          
          PATHS=./branding    
          export $(bash <(curl -fsS "https://raw.githubusercontent.com/StefanVanDyck/git-semantic-version/refs/heads/main/version.sh") | xargs)

          if [ "${number_of_changes_since_last_tag}" != "0" ]; then
            echo "Setting new version for branding ${component} to ${new_version}"
            echo "branding_version=${new_version}" >> "$GITHUB_OUTPUT"
          fi
          
          # Services
          CONFIG_VERSIONS="{}"
          DOCKER_VERSIONS="{}"
          for component in ${COMPONENTS}; do
            COMPONENT=${component}
          
            PATHS=./config/${component}      
            export $(bash <(curl -fsS "https://raw.githubusercontent.com/StefanVanDyck/git-semantic-version/refs/heads/main/version.sh") | xargs)

            if [ "${number_of_changes_since_last_tag}" != "0" ]; then
              echo "Setting new version for config ${component} to ${new_version}"
              CONFIG_VERSIONS=$(jq -c ". += {\"${component}\": \"${new_version}\"}" <<< ${CONFIG_VERSIONS})
            fi
          
            PATHS=./docker/${component}
            export $(bash <(curl -fsS "https://raw.githubusercontent.com/StefanVanDyck/git-semantic-version/refs/heads/main/version.sh") | xargs)

            if [ "${number_of_changes_since_last_tag}" != "0" ]; then
              echo "Setting new version for docker ${component} to ${new_version}"
              DOCKER_VERSIONS=$(jq -c ". += {\"${component}\": \"${new_version}\"}" <<< ${DOCKER_VERSIONS})
            fi
          done
          
          # Debug
          echo "config_versions=${CONFIG_VERSIONS}"
          echo "docker_versions=${DOCKER_VERSIONS}"
          
          echo "config_versions=${CONFIG_VERSIONS}" >> "$GITHUB_OUTPUT"
          echo "docker_versions=${DOCKER_VERSIONS}" >> "$GITHUB_OUTPUT"
    outputs:
      branding_version: ${{ steps.versions.outputs.branding_version }}
      config_versions: ${{ toJSON(steps.versions.outputs.config_versions) }}
      docker_versions: ${{ toJSON(steps.versions.outputs.docker_versions) }}

  upload-branding-to-s3:
    runs-on: [ stefan ]
    needs: get-versions
    if: ${{ needs.get-versions.outputs.branding_version != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: branding/package-lock.json

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_SHARED_INFRA_ROLE_ARN }}

      - name: Build branding website S3
        working-directory: ./branding
        env:
          VERSION: ${{ needs.get-versions.outputs.branding_version }}
        run: |
          npm install && ./deploy-to-s3.sh

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/branding-v${{ needs.get-versions.outputs.branding_version }}',
              sha: context.sha
            })

  build-and-push-docker-images:
    runs-on: [ stefan ]
    needs: get-versions
    if: ${{ needs.get-versions.outputs.docker_versions != '{}' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_SHARED_INFRA_ROLE_ARN }}

#      - name: Docker login to Amazon ECR
#        if: ${{ steps.version.outputs.number_of_changes_since_last_tag != '0' }}
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ${{ secrets.AWS_REGION }}
#        run: |
#          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
#          $(aws sts assume-role \
#            --role-arn arn:aws:iam::632683202044:role/inbo-developers-role \
#            --role-session-name MySessionName \
#            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
#            --output text))
#          aws sts get-caller-identity
#
#          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
#            | docker login --username AWS --password-stdin 632683202044.dkr.ecr.eu-west-1.amazonaws.com

#      - name: Pull docker build images
#        if: ${{ steps.version.outputs.number_of_changes_since_last_tag != '0' }}
#        run: |
#          docker pull 632683202044.dkr.ecr.eu-west-1.amazonaws.com/docker-hub/moby/buildkit:buildx-stable-1
#          docker pull 632683202044.dkr.ecr.eu-west-1.amazonaws.com/docker-hub/tonistiigi/binfmt:latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=632683202044.dkr.ecr.eu-west-1.amazonaws.com/docker-hub/moby/buildkit:buildx-stable-1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
#        with:
#          image: 632683202044.dkr.ecr.eu-west-1.amazonaws.com/docker-hub/tonistiigi/binfmt:latest

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            var-cache-apt
            var-lib-apt
            gradle-cache
            maven-cache
          key: cache-docker-${{ matrix.name }}-${{ hashFiles(format('docker/{0}/Dockerfile', matrix.name)) }}

      - name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "gradle-cache": "/gradle-cache",
              "maven-cache": "/root/.m2/repository"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and push docker images
        working-directory: ./docker
        run: |
          echo ${{ needs.get-versions.outputs.docker_versions }}
          
          for component_version in $(jq -c '. | to_entries | .[]' <<< "{\"alerts\":\"0.0.1\",\"apikey\":\"0.0.1\"}"); do
            echo "${component_version}"
            docker_name=$(jq -r '.key' <<< "${component_version}")
            version=$(jq -r '.value' <<< "${component_version}")
            echo " Releasing ${docker_name} version ${version}"
            TAG=${version} docker buildx bake --push ${docker_name} --set='*.args.BUILDPLATFORM=linux/arm64' --set='*.platform=linux/amd64,linux/arm64'
          done

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            const versions = ${{ needs.get-versions.outputs.docker_versions }};
            for (const [component, version] of Object.entries(versions)) {
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/docker-${component}-v${version}`,
                sha: context.sha
              });
            }
  deploy:
    needs:
      - upload-branding-to-s3
      - build-and-push-docker-images
    runs-on: [ stefan ]
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{needs.get-next-version.outputs.version}}',
              sha: context.sha
            })
