#name: Release new version of the portal
#run-name: ${{ github.actor }} is releasing a new version
#on:
#  push:
#    branches:
#      - 'main'
#      - 'build-and-publish-docker-images'
#jobs:
#  upload-branding-to-s3:
#    runs-on: [ self-hosted ]
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build branding website S3
#        run: |
#          cd branding && npm install && ./deploy-to-s3.sh
#        env:
#          AWS_S3_BUCKET: biodiversiteitsportaal-dev-branding
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#
#  build-and-push-docker-images:
#    runs-on: [ self-hosted ]
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build and push docker images
#        run: |
#          docker buildx bake --push
