name: Release new version of the portal
run-name: ${{ github.actor }} is releasing a new version
on:
  push:
    branches:
      - 'main'
      - 'dev'
jobs:
  get-next-version:
    # runs-on: [ self-hosted ] # does not support arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          dev-branch: dev
    outputs:
      version: ${{ steps.version.outputs.version }}

  upload-branding-to-s3:
    needs: get-next-version
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: branding/package-lock.json

      - name: Build branding website S3
        working-directory: ./branding
        env:
          VERSION: ${{needs.get-next-version.outputs.version}}
          AWS_S3_BUCKET: biodiversiteitsportaal-dev-branding
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          npm install && ./deploy-to-s3.sh

  build-and-push-docker-images:
    needs: get-next-version
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4

      - name: Build and push docker images
        working-directory: ./docker
        env:
          TAG: ${{needs.get-next-version.outputs.version}}
        run: |
          docker buildx bake --push all --set='*.args=BUILDPLATFORM=linux/arm64' --set='*.platform=linux/amd64,linux/arm64'


  release:
    needs:
      - get-next-version
      - upload-branding-to-s3
      - build-and-push-docker-images
    runs-on: [ self-hosted ]
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{needs.get-next-version.outputs.version}}',
              sha: context.sha
            })
