name: Update translations
run-name: ${{ github.actor }} is checking for translations updates

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-translations:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create commit
        id: update-translations
        env:
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
        run: |
          set -e -o pipefail
          
          git checkout update-translations || git checkout -b update-translations
          
          ./scripts/update-translations.sh
          
          git config --global user.email "support.natuurdata@inbo.be"
          git config --global user.name "Github Actions"
                
          if [ -n "$(git status --porcelain)" ]; then
            git add '**/crowdin/messages*.properties'
            git commit -m "Github actions: automated update of translations"
            git push --set-upstream origin update-translations
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "no changes";
            echo "changes=false" >> "$GITHUB_OUTPUT"
          fi      

      - name: Create Pull Request
        uses: actions/github-script@v7
        if: steps.create-commit.outputs.changes == 'true'
        with:
          github-token: ${{ secrets.GIT_PAT_TOKEN }}
          script: |
            const openPrs = await github.rest.pulls.list({
              owner: 'inbo',
              repo: 'vlaams-biodiversiteitsportaal',
              state: 'open',
              head: 'inbo:update-translations'
            });
            if (openPrs.data.length === 1) {
              console.log(`PR already exists: ${openPrs.data[0].html_url}`);
              return;
            }
            const result = await github.rest.pulls.create({
              title: 'Automated version update',
              owner: 'inbo',
              repo: 'vlaams-biodiversiteitsportaal',
              head: 'update-translations',
              base: '${{ github.ref_name }}',
              body: 'This PR is auto-generated by [a github action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) in [inbo/vlaams-biodiversiteitsportaal](https://github.com/inbo/vlaams-biodiversiteitsportaal).'
            });
            github.rest.issues.addLabels({
              owner: 'inbo',
              repo: 'vlaams-biodiversiteitsportaal',
              issue_number: result.data.number,
              labels: ['translation', 'automated pr']
            });