apiVersion: 1

datasources:
  - name: X-Ray DEV
    type: grafana-x-ray-datasource
    uid: x-ray-dev
    isDefault: false
    jsonData:
      defaultRegion: eu-west-1
      assumeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID_DEV}:role/inbo-vbp-grafana-dev-role

  - name: cloudwatch DEV
    type: cloudwatch
    uid: cloudwatch-dev
    isDefault: true
    jsonData:
      defaultRegion: eu-west-1
      assumeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID_DEV}:role/inbo-vbp-grafana-dev-role
      customMetricsNamespaces: Inbo/VBP
      tracingDatasourceUid: x-ray-dev
