apiVersion: 1

datasources:
  - name: X-Ray UAT
    type: grafana-x-ray-datasource
    uid: x-ray-uat
    isDefault: false
    jsonData:
      defaultRegion: eu-west-1
      assumeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID_UAT}:role/inbo-vbp-grafana-uat-role

  - name: cloudwatch UAT
    type: cloudwatch
    uid: cloudwatch-uat
    isDefault: true
    jsonData:
      defaultRegion: eu-west-1
      assumeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID_UAT}:role/inbo-vbp-grafana-uat-role
      customMetricsNamespaces: Inbo/VBP
      tracingDatasourceUid: x-ray-uat
