apiVersion: 1
groups:
    - orgId: 1
      name: Test
      folder: VBP - UAT
      interval: 1m
      rules:
        - uid: bf1to65xbdiwwf
          title: Test google chat
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: cloudwatch-uat
              model:
                dimensions: {}
                expression: |-
                    fields @timestamp, @message, @logStream |
                      filter @message like /\[ERROR\]/ |
                      sort @timestamp desc |
                      parse @message /\[ERROR\](?<error>.+?)(?: \[AWS-XRAY-TRACE-ID: (?<@xrayTraceId>.+?)@(?<@xraySegementId>.+?)\])?\n/ |
                      parse @logStream /^(?<service>.+?)\/(?<container>.+?)\/(?<containerId>.+)/ |
                      stats count(*) as count by service, container, containerId, error, bin(1m) |
                      limit 10
                id: ""
                intervalMs: 60000
                label: ""
                logGroups:
                    - arn: /inbo/vbp/ecs
                      name: /inbo/vbp/ecs
                matchExact: true
                maxDataPoints: 100
                metricEditorMode: 0
                metricName: ""
                metricQueryType: 0
                namespace: ""
                period: ""
                queryMode: Logs
                refId: A
                region: default
                sqlExpression: ""
                statistic: Average
                statsGroups:
                    - service
                    - container
                    - containerId
                    - error
                    - bin(1m)
            - refId: B
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: sum
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 900
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ecs-logs-uat
          panelId: 1
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: ecs-logs-uat
            __panelId__: "1"
            description: <code>{{ reReplaceAll "\\x1b\\[[;\\d]*[A-Za-z]" "" $labels.error }}</code>
            summary: 'Container {{ $labels.container }} for service {{ $labels.service }} logged an error:'
          isPaused: false
        - uid: df1weyr65h4w0f
          title: Running tasks
          condition: E
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cloudwatch-uat
              model:
                dimensions:
                    ClusterName: inbo-vbp-cluster
                    ServiceName: '*'
                expression: ""
                id: ""
                intervalMs: 1000
                label: ""
                logGroups: []
                matchExact: true
                maxDataPoints: 43200
                metricEditorMode: 0
                metricName: RunningTaskCount
                metricQueryType: 0
                namespace: ECS/ContainerInsights
                period: ""
                queryMode: Metrics
                refId: A
                region: default
                sqlExpression: ""
                statistic: Average
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cloudwatch-uat
              model:
                datasource:
                    type: cloudwatch
                    uid: cloudwatch-uat
                dimensions:
                    ClusterName: inbo-vbp-cluster
                    ServiceName: '*'
                expression: ""
                hide: false
                id: ""
                intervalMs: 60000
                label: ""
                logGroups: []
                matchExact: true
                maxDataPoints: 43200
                metricEditorMode: 0
                metricName: DesiredTaskCount
                metricQueryType: 0
                namespace: ECS/ContainerInsights
                period: ""
                queryMode: Metrics
                refId: B
                region: default
                sqlExpression: ""
                statistic: Average
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B - $A
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: C
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: D
                type: reduce
            - refId: E
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: D
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: E
                type: threshold
          dashboardUid: portal-health-uat
          panelId: 97
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: portal-health-uat
            __panelId__: "97"
            summary: '{{ $labels.ServiceName }} doesn''t have enough running tasks'
          isPaused: false
        - uid: bf1wf8w1j13pce
          title: Load Balancer Target Health
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cloudwatch-uat
              model:
                dimensions:
                    LoadBalancer: app/inbo-vbp-public/a744d69ec78da33a
                    TargetGroup: '*'
                expression: ""
                id: ""
                intervalMs: 60000
                label: ""
                logGroups: []
                matchExact: true
                maxDataPoints: 43200
                metricEditorMode: 0
                metricName: UnHealthyHostCount
                metricQueryType: 0
                namespace: AWS/ApplicationELB
                period: ""
                queryMode: Metrics
                refId: A
                region: default
                sqlExpression: ""
                statistic: Maximum
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: portal-health-uat
          panelId: 168
          noDataState: NoData
          execErrState: Error
          for: 5m
          annotations:
            __dashboardUid__: portal-health-uat
            __panelId__: "168"
            summary: Load balancer target {{ $labels.TargetGroup }} has unhealthy hosts
          isPaused: false
        - uid: ef1whc9e5reo0f
          title: AWS RUM Error
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cloudwatch-uat
              model:
                dimensions:
                    application_name: inbo-vbp-portal
                expression: ""
                id: ""
                intervalMs: 60000
                label: ""
                logGroups: []
                matchExact: true
                maxDataPoints: 43200
                metricEditorMode: 0
                metricName: JsErrorCount
                metricQueryType: 0
                namespace: AWS/RUM
                period: ""
                queryMode: Metrics
                refId: A
                region: default
                sqlExpression: ""
                statistic: Sum
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            description: ""
            runbook_url: ""
            summary: Some JS Errors were detected in the front-end
          labels:
            "": ""
          isPaused: false
