apiVersion: 1
contactPoints:
    - orgId: 1
      name: Google Chat
      receivers:
        - uid: google-chat-vbp-alerts
          type: googlechat
          settings:
            url: ${GOOGLE_CHAT_WEBHOOK_URL}
            title: |
              {{ template "vbp.google.title" . }}
            message: |
              {{ template "vbp.google.message" . }}
          disableResolveMessage: false
        - uid: google-chat-vbp-alerts-custom
          type: webhook
          settings:
            url: ${GOOGLE_CHAT_WEBHOOK_URL}
            customPayload: |
              {{ template "vbp.google.custom" . }}
          disableResolveMessage: false
