apiVersion: 1
groups:
    - orgId: 1
      name: Cloudwatch alerts
      folder: VBP - DEV
      interval: 5m
      rules:
        - uid: cloudwatch-logs-dev
          title: Errors and warnings
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: cloudwatch-dev
              model:
                datasource:
                    type: cloudwatch
                    uid: cloudwatch-dev
                dimensions: {}
                expression: |-
                    fields @timestamp, @message, @logStream |
                     filter @message like /\[ERROR\]/ |
                     stats count() by @logStream, bin(1m) |
                     sort @timestamp desc |
                     limit 100
                id: ""
                intervalMs: 60000
                label: ""
                logGroups:
                    - arn: /inbo/vbp/ecs
                      name: /inbo/vbp/ecs
                    - arn: /inbo/vbp/lambda
                      name: /inbo/vbp/lambda
                    - arn: /inbo/vbp/pipelines
                      name: /inbo/vbp/pipelines
                matchExact: true
                maxDataPoints: 43200
                metricEditorMode: 0
                metricName: ""
                metricQueryType: 0
                namespace: ""
                period: ""
                queryMode: Logs
                refId: A
                region: eu-west-1
                sqlExpression: ""
                statistic: Average
                statsGroups:
                    - '@logStream'
                    - bin(1m)
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                hide: false
                intervalMs: 60000
                maxDataPoints: 43200
                reducer: sum
                refId: B
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                hide: false
                intervalMs: 60000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: portal-health
          panelId: 170
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: portal-health
            __panelId__: "170"
            description: An error was logged by {{ $labels.@logStream }}
            summary: Error occurred in the logs
          labels: {}
          isPaused: false
