apiVersion: 1
groups:
    - orgId: 1
      name: Cloudwatch alerts
      folder: VBP - DEV
      interval: 5m
      rules:
        - uid: cloudwatch-logs-dev
          title: Errors and warnings
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: cloudwatch-dev
              model:
                datasource:
                    type: cloudwatch
                    uid: cloudwatch-dev
                dimensions: {}
                expression: |-
                  fields @timestamp, @message, @logStream |
                   filter @message like /\[ERROR\]/ |
                   sort @timestamp desc |
                   parse @message /\[ERROR\](?<@error>.+?)(?: \[AWS-XRAY-TRACE-ID: (?<@xrayTraceId>.+?)@(?<@xraySegementId>.+?)\])?\n/ |
                   stats count(*) as count by @logStream, @error, bin(1m) |
                   limit 100
                id: ""
                intervalMs: 60000
                label: ""
                logGroups:
                    - arn: /inbo/vbp/ecs
                      name: /inbo/vbp/ecs
                matchExact: true
                maxDataPoints: 43200
                metricEditorMode: 0
                metricName: ""
                metricQueryType: 0
                namespace: ""
                period: ""
                queryMode: Logs
                refId: A
                region: default
                sqlExpression: ""
                statistic: Average
                statsGroups:
                    - '@logStream'
                    - '@error'
                    - bin(1m)
            - refId: B
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: sum
                refId: B
                settings:
                    mode: dropNN
                type: reduce
            - refId: C
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: portal-health
          panelId: 170
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            __dashboardUid__: portal-health
            __panelId__: "170"
            description: An error was logged by {{ $labels }}
            summary: Error occurred in the logs
          labels:
            env: dev
          isPaused: false
