apiVersion: 1
contactPoints:
    - orgId: 1
      name: Google Chat
      receivers:
        - uid: google-chat-vbp-alerts
          type: webhook
          settings:
            url: ${GOOGLE_CHAT_WEBHOOK_URL}
            headers:
                Content-Type: application/json
            httpMethod: POST
            payload:
                template: '{{ template "vbp.google.cardsV2" . }}'
          disableResolveMessage: false

    - orgId: 1
      name: Google Chat Without Resolve
      receivers:
        - uid: google-chat-vbp-alerts-without-resolve
          type: webhook
          settings:
            url: ${GOOGLE_CHAT_WEBHOOK_URL}
            headers:
                Content-Type: application/json
            httpMethod: POST
            payload:
                template: '{{ template "vbp.google.cardsV2" . }}'
          disableResolveMessage: true

muteTimes:
  - orgId: 1
    name: during-working-hours
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '18:00'
        weekdays: ['monday:friday']
        location: 'Europe/Brussels'

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
    routes:
      - receiver: Google Chat Without Resolve
        object_matchers:
          - - notify
            - =
            - google
        mute_time_intervals:
          - during-working-hours
