apiVersion: 1
contactPoints:
    - orgId: 1
      name: Google Chat
      receivers:
        - uid: google-chat-vbp-alerts
          type: webhook
          settings:
            url: ${GOOGLE_CHAT_WEBHOOK_URL}
            headers:
                Content-Type: application/json
            httpMethod: POST
            payload:
                template: '{{ template "vbp.google.cardsV2" . }}'
          disableResolveMessage: false
        - uid: google-chat-vbp-alerts-without-resolve
          type: webhook
          settings:
            url: ${GOOGLE_CHAT_WEBHOOK_URL}
            headers:
                Content-Type: application/json
            httpMethod: POST
            payload:
                template: '{{ template "vbp.google.cardsV2" . }}'
          disableResolveMessage: true

deleteContactPoints:
  - orgId: 1
    uid: google-chat-vbp-alerts-custom

muteTimes:
  - orgId: 1
    name: during-working-hours
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '18:00'
        weekdays: ['monday:friday']
        location: 'Europe/Brussels'

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
    routes:
      - receiver: google-chat-vbp-alerts-without-resolve
        object_matchers:
          - - notify
            - =
            - google
          - - resolve
            - =
            - 'false'
        active_time_intervals:
          - during-working-hours
      - receiver: google-chat-vbp
        object_matchers:
          - - notify
            - =
            - google
        active_time_intervals:
          - during-working-hours
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
