apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: ['grafana_folder', 'alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: google-chat-vbp-alerts
        matchers:
          - alertname = "Errors logged by portal services"
        mute_time_intervals:
          - outside-working-hours
