apiVersion: 1
templates:
- orgId: 1
  name: vbp.google.title
  template: |-
    {{ define "vbp.google.title" }}
    🚨 {{.CommonLabels.alertname }} is {{ .Status }}
    {{ end }}
- orgId: 1
  name: vbp.google.message
  template: |-
    {{ define "vbp.google.message" }}
      {{ if .Alerts.Firing -}}
        {{ len .Alerts.Firing }} firing alert(s)
        {{ range .Alerts.Firing }}
        <b>{{ trimSpace .Annotations.summary }}</b>
        {{- if eq $.CommonLabels.alertname "Errors logged by portal services" -}}<a href={{ template "vbp.grafana.logsDashboardLink" . }}>🖹</a> <a href={{ .SilenceURL }}>🔕</a>{{ end }}
        {{ trimSpace .Annotations.description }}
        {{ end }}
      {{ end }}

      {{ if .Alerts.Resolved -}}
        {{ len .Alerts.Resolved }} resolved alert(s)
        {{ range .Alerts.Resolved }}
        {{ trimSpace .Annotations.summary }}
        {{- end }}
      {{ end }}
    {{ end }}
- orgId: 1
  name: vbp.google.cardsV2
  template: |-
    {{ define "vbp.google.cardsV2" -}}
    {
      "cardsV2": [
        {
          "card": {
            "header": {
              "title": "{{ len .Alerts }} Problem(s) @ {{ .CommonLabels.grafana_folder }}",
              "imageUrl": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.3TogH2tQvYaU5cv4-EEcvwHaHa%26pid%3DApi&f=1&ipt=39902d7c82156c8499eb40496594a16b7a1d97c47c7a284eb7d95465e04b0251",
              "imageType": "SQUARE"
            },
            "sections": [
              {
                "collapsible": true,
                "collapseControl": {
                  "horizontalAlignment": "CENTER",
                  "collapseButton": {
                    "icon": {
                      "materialIcon": {
                        "name": "keyboard_arrow_up"
                      }
                    },
                    "text": "Show less",
                    "type": "BORDERLESS"
                  },
                  "expandButton": {
                    "icon": {
                      "materialIcon": {
                        "name": "keyboard_arrow_down"
                      }
                    },
                    "text": "Show more",
                    "type": "BORDERLESS"
                  }
                },
                "uncollapsibleWidgetsCount": 4,
                "widgets": [
                {{ range $idx, $alert := .Alerts -}}
                {{- if gt $idx 0 -}}
                  ,
                  {{ $prev_index := len (slice (printf "%*s" $idx "") 1)}}
                  {{- if ne (index $.Alerts $prev_index).Labels.alertname .Labels.alertname -}}
                  {
                    "textParagraph": {
                      "text": "{{ .Labels.alertname }}"
                    }
                  },    
                  {{- end -}}
                  {{- else -}}
                  {
                    "textParagraph": {
                      "text": "{{ .Labels.alertname }}"
                    }
                  },  
                {{- end }}
                {{ template "vbp.google.custom.alert" $alert }}
                {{- end }}
                ]
              }
            ]
          }
        }
      ]
    }
    {{- end }}
    
    {{ define "vbp.google.custom.alert" -}}
    {
      "decoratedText": {
        "topLabel": "{{ if .GeneratorURL }}<a href=\"{{ .GeneratorURL }}\">{{ end }}{{ reReplaceAll "\"" "\\\"" .Annotations.summary }}{{ if .GeneratorURL }}</a>{{ end }}",
        "text": "<font color=\"{{ if eq .Status "resolved" -}}#00b11d{{- else -}}#b10000{{- end }}\">{{ reReplaceAll "\"" "\\\""  .Annotations.description }}</font>",
        "startIcon": {
          "materialIcon": {
            "name": "{{ if eq .Status "resolved" -}}check{{- else -}}error{{- end }}",
            "fill": true,
            "weight": 200,
            "grade": -25
          }
        }
      }
    },
    {
      "chipList": {
        "chips": [
          {{ if .PanelURL }}
          {
            "label": "View in dashboard",
            "icon": {
              "materialIcon": {
                "name": "monitoring"
              }
            },
            "onClick": {
              "openLink": {
                "url": "{{ if eq .Labels.alertname "Errors in ECS logs" }}{{ template "logs-dashboard-link" . }}{{ else }}{{ .PanelURL }}{{ end }}"
              }
            }
          },
          {{ end }}
          {
            "label": "Silence",
            "icon": {
              "materialIcon": {
                "name": "notifications_off"
              }
            },
            "onClick": {
              "openLink": {
                "url": "{{ .SilenceURL }}"
              }
            }
          }
        ]
      }
    }
    {{- end}}
    
    {{ define "logs-dashboard-link" -}}
      {{ $log_stream:= "" -}}
      {{ if .Annotations.container }}{{ $log_stream = .Annotations.container }}{{ end -}}
      {{ if .Annotations.containerId }}{{ $log_stream = print $log_stream "%5C%2F" .Annotations.containerId }}{{ end -}}
      {{ .PanelURL -}}
      {{ if .Annotations.service }}&var-service{{ .Annotations.service }}{{ end -}}
      {{ if gt (len $log_stream) 0 }}&var-log_stream={{ $log_stream }}{{ end -}}
    {{ end }}
