apiVersion: 1
templates:
- orgId: 1
  name: vbp.google.cardsV2
  template: |-
    {{ define "vbp.google.cardsV2" -}}
    {
      "cardsV2": [
        {
          "card": {
            "header": {
              "title": "{{ len .Alerts }} Problem(s) @ {{ .CommonLabels.grafana_folder }}",
              "imageUrl": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.3TogH2tQvYaU5cv4-EEcvwHaHa%26pid%3DApi&f=1&ipt=39902d7c82156c8499eb40496594a16b7a1d97c47c7a284eb7d95465e04b0251",
              "imageType": "SQUARE"
            },
            "sections": [
              {
                "collapsible": true,
                "collapseControl": {
                  "horizontalAlignment": "CENTER",
                  "collapseButton": {
                    "icon": {
                      "materialIcon": {
                        "name": "keyboard_arrow_up"
                      }
                    },
                    "text": "Show less",
                    "type": "BORDERLESS"
                  },
                  "expandButton": {
                    "icon": {
                      "materialIcon": {
                        "name": "keyboard_arrow_down"
                      }
                    },
                    "text": "Show more",
                    "type": "BORDERLESS"
                  }
                },
                "uncollapsibleWidgetsCount": 4,
                "widgets": [
                {{ range $idx, $alert := .Alerts -}}
                {{- if gt $idx 0 -}}
                  ,
                  {{ $prev_index := len (slice (printf "%*s" $idx "") 1)}}
                  {{- if ne (index $.Alerts $prev_index).Labels.alertname .Labels.alertname -}}
                  {
                    "textParagraph": {
                      "text": "{{ .Labels.alertname }}"
                    }
                  },    
                  {{- end -}}
                  {{- else -}}
                  {
                    "textParagraph": {
                      "text": "{{ .Labels.alertname }}"
                    }
                  },  
                {{- end }}
                {{ template "vbp.google.cardsV2.alert" $alert }}
                {{- end }}
                ]
              }
            ]
          }
        }
      ]
    }
    {{- end }}
    
    {{ define "vbp.google.cardsV2.alert" -}}
    {{ $summary := data.ToJSON .Annotations.summary -}}
    {{ $summary = slice $summary 1 (len (slice (printf "%*s" (len $summary) "") 1))  -}}
    {{ $description := data.ToJSON .Annotations.description -}}
    {
      "decoratedText": {
        "text": "<font color=\"{{ if eq .Status "resolved" -}}#00b11d{{- else -}}#b10000{{- end }}\">{{ $summary }}</font>",
        "bottomLabel": {{ $description }},
        "startIcon": {
          "materialIcon": {
            "name": "{{ if eq .Status "resolved" -}}check{{- else -}}error{{- end }}",
            "fill": true,
            "weight": 200,
            "grade": -25
          }
        }
      }
    },
    {
      "chipList": {
        "chips": [
          {{ if .Annotations.consoleLink }}
          {
            "label": "View on AWS",
            "icon": {
              "materialIcon": {
                "name": "cloud"
              }
            },
            "onClick": {
              "openLink": {
                "url": "{{ .Annotations.consoleLink }}"
              }
            }
          },
          {{ end }}
          {{ if .PanelURL }}
          {
            "label": "View in dashboard",
            "icon": {
              "materialIcon": {
                "name": "monitoring"
              }
            },
            "onClick": {
              "openLink": {
                "url": "{{ if eq .Labels.alertname "Errors in ECS logs" }}{{ template "logs-dashboard-link" . }}{{ else }}{{ .PanelURL }}{{ end }}"
              }
            }
          },
          {{ end }}
          {
            "label": "Silence",
            "icon": {
              "materialIcon": {
                "name": "notifications_off"
              }
            },
            "onClick": {
              "openLink": {
                "url": "{{ .SilenceURL }}"
              }
            }
          }
        ]
      }
    }
    {{- end}}
    
    {{ define "logs-dashboard-link" -}}
      {{ $log_stream:= "" -}}
      {{ if .Labels.container }}{{ $log_stream = .Labels.container }}{{ end -}}
      {{ if .Labels.containerId }}{{ $log_stream = print $log_stream "%5C%2F" .Labels.containerId }}{{ end -}}
      {{ .PanelURL -}}
      {{ if .Labels.service }}&var-service={{ .Labels.service }}{{ end -}}
      {{ if gt (len $log_stream) 0 }}&var-log_stream={{ $log_stream }}{{ end -}}
      &var-query=%5C%5BERROR%5C%5D
    {{- end }}
