apiVersion: 1
templates:
- orgID: 1
  name: vbp.google.title
  template: |-
    {{ define "vbp.google.title" }}
    🚨 {{.CommonLabels.alertname }} is {{ .Status }}
    {{ end }}
- orgID: 1
  name: vbp.google.message
  template: |-
    {{ define "vbp.google.message" }}
      {{ if .Alerts.Firing -}}
        {{ len .Alerts.Firing }} firing alert(s)
        {{ range .Alerts.Firing }}
        <b>{{ trimSpace .Annotations.summary }}</b> 
        {{- if eq $.CommonLabels.alertname "Errors logged by portal services" -}}<a href={{ template "vbp.grafana.logsDashboardLink" . }}>🖹</a> <a href={{ .SilenceURL }}>🔕</a>{{ end }}
        {{ trimSpace .Annotations.description }}
        {{ end }}
      {{ end }}
    
      {{ if .Alerts.Resolved -}}
        {{ len .Alerts.Resolved }} resolved alert(s)
        {{ range .Alerts.Resolved }}
        {{ trimSpace .Annotations.summary }}
        {{- end }}
      {{ end }}
    {{ end }}
- orgID: 1
  name: vbp.grafana.logsDashboardLink
  template: |-
    {{ define "vbp.grafana.logsDashboardLink" }}
      {{ .DashboardURL }}&var-service={{.Labels.service}}&var-log_stream={{.Labels.container}}%5C%2F{{.Labels.containerId}}
    {{ end }}
