advancedTaxaField: taxa
ala:
  baseURL: http://la-flanders.org
alerts:
  apiKey: a5c2e4d1-324c-4bc2-8770-2a2aa092df49
  baseUrl: ''
  myannotation:
    enabled: false
allowedImageEditingRoles: ROLE_ADMIN
alwaysshow:
  imagetab: true
authenticateOnlyIfLoggedInFilterPattern: /occurrences/*,/explore/your-area,/query,/proxy/download/*
authorise:
  roles: ROLE_ADMIN,ROLE_COLLECTION_ADMIN
bie:
  baseURL: http://species.la-flanders.org
  baseUrl: http://species.la-flanders.org
  searchPath: /search
bieApiKey: 5bd6d4fc-3f1c-4fa2-903a-7ec771c02999
bieService:
  baseUrl: http://species-ws.la-flanders.org
biocache:
  ajax:
    useProxy: false
  apiKey: ae1cc2a8-0509-4792-8e62-ded96510d5cc
  baseUrl: http://records-ws.la-flanders.org
  downloads:
    extra: dataResourceUid,dataResourceName.p
  groupedFacetsUrl: file:///data/ala-hub/config/grouped_facets_default.json
  indexedFieldsUrl: http://records-ws.la-flanders.org/index/fields
  queryContext: -_nest_parent_:*
  url: http://records.la-flanders.org
biocacheServiceUrl: http://records-ws.la-flanders.org
biocacheServicesUrl: http://records-ws.la-flanders.org
casProperties: casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilterPattern,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath
casServerLoginUrl: http://auth.la-flanders.org/cas/login
casServerLogoutUrl: http://auth.la-flanders.org/cas/logout
casServerName: http://auth.la-flanders.org
casServerUrlPrefix: http://auth.la-flanders.org/cas
clubRoleForHub: ROLE_ADMIN
collections:
  baseUrl: http://collections.la-flanders.org
collectory:
  baseUrl: http://collections.la-flanders.org
  resources: http://collections.la-flanders.org/public/resources.json
dataQualityChecksUrl: https://docs.google.com/spreadsheet/pub?key=0AjNtzhUIIHeNdHJOYk1SYWE4dU1BMWZmb2hiTjlYQlE&single=true&gid=0&output=csv
dataquality:
  apiKey: 28f72d39-6c8b-44fc-8184-cd81f6ea518a
  baseUrl: https://dataquality.ala.org.au/
  disableAllFiltersByDefault: false
  enabled: false
  expandFiltersByDefault: true
  learnmore_link: ''
  warningOn: false
defaultListView: ''
defaultLocale: en
disableCAS: false
doi:
  mintDoi: false
doiService:
  baseUrl: https://doi.ala.org.au
downloads:
  checklistDownloadUrl: http://records-ws.la-flanders.org/occurrences/facets/download
  customSections:
    misc: qualityAssertions,miscellaneousFields
  defaultDownloadFormat: dwc
  dwcExtraFields: data_resource_uid
  fieldguideDownloadUrl: ''
  indexedDownloadUrl: http://records-ws.la-flanders.org/occurrences/offline/download
  indexedFieldsUrl: http://records-ws.la-flanders.org/index/fields
  legacy:
    defaultFields: id,data_resource_uid,data_resource,license,catalogue_number,taxon_concept_lsid,raw_taxon_name,raw_common_name,taxon_name,rank,common_name,kingdom,phylum,class,order,family,genus,species,subspecies,institution_code,collection_code,locality,raw_latitude,raw_longitude,raw_datum,latitude,longitude,datum,coordinate_precision,coordinate_uncertainty,country,state,cl959,min_elevation_d,max_elevation_d,min_depth_d,max_depth_d,individual_count,recorded_by,year,month,day,verbatim_event_date,basis_of_record,raw_basis_of_record,sex,preparations,information_withheld,data_generalizations,outlier_layer,taxonomic_kosher,geospatial_kosher"
  staticDownloadsUrl: ''
  termsOfUseUrl: ''
dwc:
  exclude: dataHubUid,dataProviderUid,institutionUid,year,month,day,left,right,provenance,taxonID,preferredFlag,outlierForLayers,speciesGroups,associatedMedia,images,userQualityAssertion,speciesHabitats,duplicationType,taxonomicIssues,subspeciesID,nameMatchMetric,sounds
ecodata:
  baseURL: ''
endpoints:
  enabled: false
events:
  enabled: false
  eventUrl: https://events.la-flanders.org/?view=EVENTS&eventHierarchy=
  graphql: https://api.la-flanders.org/event/graphql
exploreYourArea:
  lat: 16.942
  lng: 1.261
  location: Australia
facets:
  cached: species_group,species_subgroup,state,country,institution_uid,collection_uid,data_resource_uid
  customOrder: ''
  defaultColourBy: ''
  defaultSelected: basis_of_record,taxon_name,collection_uid,data_resource_uid,year,species_group
  exclude: ''
  hide: ''
  include: ''
  includeDynamicFacets: false
  limit: 100
  max: 32
fieldguide:
  url: ''
filetype:
  shapefile:
    hidden: false
geocode:
  region: AU
google:
  apikey: get-a-google-api-key
grails:
  resources:
    work:
      dir: /data/ala-hub/cache
  serverURL: http://records.la-flanders.org
headerAndFooter:
  baseURL: http://branding.la-flanders.org
  version: 2
image:
  baseUrl: http://images.la-flanders.org
images:
  baseUrl: http://images.la-flanders.org
  images:
    metadataUrl: ''
  metadataUrl: http://images.la-flanders.org/image/details?imageId=
  viewerUrl: http://images.la-flanders.org/image/viewer?imageId=
info:
  app:
    description: Vlaams Biodiversiteitsportaal
largeDownloadRole: ROLE_LARGE_DOWNLOAD
layersservice:
  baseUrl: http://spatial.la-flanders.org/ws
  url: http://spatial.la-flanders.org/ws
logger:
  baseUrl: http://logger.la-flanders.org/service
loggerURL: http://logger.la-flanders.org/service
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
map:
  cloudmade:
    key: BC9A493B41014CAABB98F0471D759707
  defaultFacetMapColourBy: ''
  defaultLatitude: 16.942
  defaultLongitude: 1.261
  defaultZoom: 5
  height: 600
  minimal:
    url: https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png
  overlay:
    url: http://spatial.la-flanders.org/geoserver/gwc/service/wms
  pointColour: df4a21
  zoomOutsideScopedRegion: true
mapdownloads:
  baseLayers:
    states:
      displayName: States & territories
      i18nCode: baselayer.states
      name: aus1
maxDownloadRecords: ''
mdba:
  basinChampions: https://biocollect.ala.org.au/mdba/project/index/4d15b4df-c05b-41bd-ac5b-8a65c9e37d17
  regions: http://mdba-regions.ala.org.au/
organisation:
  baseUrl: http://la-flanders.org
pdfgen:
  baseURL: http://pdfgen.ala.org.au
privacyPolicy: ''
security:
  cas:
    appServerName: http://records.la-flanders.org
    authCookieName: ALA-Auth
    authenticateOnlyIfLoggedInFilterPattern: /occurrences/*,/explore/your-area,/query,/proxy/download/*,/
    bypass: false
    casServerLoginUrl: http://auth.la-flanders.org/cas/login
    casServerLogoutUrl: http://auth.la-flanders.org/cas/logout
    casServerName: http://auth.la-flanders.org
    casServerUrlPrefix: http://auth.la-flanders.org/cas
    enabled: true
    loginUrl: http://auth.la-flanders.org/cas/login
    logoutUrl: http://auth.la-flanders.org/cas/logout
    uriFilterPattern: /admin/*,/alaAdmin/*,/download/*
  jwt:
    clientId: ''
    discoveryUri: http://auth.la-flanders.org/cas/oidc/.well-known
  oidc:
    enabled: true # Cannot disable oidc :(
    discoveryUri: http://auth.la-flanders.org/cas/oidc/.well-known
    scope: openid,profile,email,ala,roles, user_defined
    client-id: "ala_hub"
    secret: "ala_hub-oidc-super-secret"
server:
  address: 127.0.0.1
  contextPath: ''
  port: 8080
serverName: http://records.la-flanders.org
sightings:
  baseUrl: ''
skin:
  attribution: ''
  dataQualityLink:
    show: false
    text: not set
    url: ''
  exploreUrl: https://www.ala.org.au/explore-by-location/
  favicon: https://raw.githubusercontent.com/living-atlases/artwork/master/favicon.ico
  fluidLayout: true
  homeUrl: http://la-flanders.org
  layout: ala
  orgNameLong: Vlaams Biodiversiteitsportaal
  orgNameShort: LA Flanders
  taxaLinks:
    baseUrl: http://species.la-flanders.org/species/
  useAlaBie: true
  useAlaImageService: true
  useAlaSpatialPortal: true
spatial:
  baseURL: http://spatial.la-flanders.org
  baseUrl: http://spatial.la-flanders.org
  params: ''
speciesList:
  baseURL: http://lists.la-flanders.org
  preferredListName: ALA Preferred Species Images
  preferredSpeciesListDruid: dr4778
speciesListToolUrl: http://lists.la-flanders.org/speciesListItem/list/
specieslist:
  baseUrl: http://lists.la-flanders.org/ws
stateConservationListPath:
  AustralianCapitalTerritory: /speciesListItem/list/dr649
  NewSouthWales: /speciesListItem/list/dr650
  NorthernTerritory: /speciesListItem/list/dr651
  Queensland: /speciesListItem/list/dr652
  SouthAustralia: /speciesListItem/list/dr653
  Tasmania: /speciesListItem/list/dr654
  Victoria: /speciesListItem/list/dr655
  WesternAustralia: /speciesListItem/list/dr2201
supportEmail: support@la-flanders.org
table:
  displayDynamicProperties: false
uriExclusionFilterPattern: /occurrences/shapeUpload,/images.*,/css.*,/js.*,.*json,/help/.*
uriFilterPattern: /admin/*,/alaAdmin/*,/download/*
useDownloadPlugin: true
userCharts: false
userDetails:
  url: http://auth.la-flanders.org/userdetails/
userdetails:
  api:
    url: http://auth.la-flanders.org/userdetails/
  baseUrl: http://auth.la-flanders.org
  url: http://auth.la-flanders.org/userdetails/
  web:
    url: http://auth.la-flanders.org/userdetails/
webservice:
  apiKey: ae1cc2a8-0509-4792-8e62-ded96510d5cc
  client-id: ''
  client-secret: ''
  jwt: false
  jwt-scopes: ''