---
### OIDC Credentials ###
security:
  jwt:
    clientId: ala_hub
  oidc:
    clientId: "ala_hub"
    secret: "ala_hub-oidc-super-secret"
webservice:
  client-id: "ala_hub"
  client-secret: "ala_hub-oidc-super-secret"

advancedTaxaField: taxa
alerts:
  apiKey: a5c2e4d1-324c-4bc2-8770-2a2aa092df49
  baseUrl: ''
  myannotation:
    enabled: false
allowedImageEditingRoles: ROLE_ADMIN
alwaysshow:
  imagetab: true
authenticateOnlyIfLoggedInFilterPattern: /occurrences/*,/explore/your-area,/query,/proxy/download/*
authorise:
  roles: ROLE_ADMIN,ROLE_COLLECTION_ADMIN
bie:
  baseURL: ${common.protocol}://species.${common.domain}
  baseUrl: ${common.protocol}://species.${common.domain}
  searchPath: /search
bieApiKey: 5bd6d4fc-3f1c-4fa2-903a-7ec771c02999
bieService:
  baseUrl: ${common.protocol}://species-ws.${common.domain}
biocache:
  ajax:
    useProxy: false
  apiKey: ae1cc2a8-0509-4792-8e62-ded96510d5cc
  baseUrl: ${common.protocol}://records-ws.${common.domain}
  downloads:
    extra: dataResourceUid,dataResourceName.p
  groupedFacetsUrl: file:///data/ala-hub/config/grouped_facets_default.json
  indexedFieldsUrl: ${common.protocol}://records-ws.${common.domain}/index/fields
  queryContext: -_nest_parent_:*
  url: ${common.protocol}://records.${common.domain}
biocacheServiceUrl: ${common.protocol}://records-ws.${common.domain}
biocacheServicesUrl: ${common.protocol}://records-ws.${common.domain}
casProperties: casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilterPattern,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath
casServerLoginUrl: ${common.protocol}://auth.${common.domain}/cas/login
casServerLogoutUrl: ${common.protocol}://auth.${common.domain}/cas/logout
casServerName: ${common.protocol}://auth.${common.domain}
casServerUrlPrefix: ${common.protocol}://auth.${common.domain}/cas
clubRoleForHub: ROLE_ADMIN
collections:
  baseUrl: ${common.protocol}://collections.${common.domain}
collectory:
  baseUrl: ${common.protocol}://collections.${common.domain}
  resources: ${common.protocol}://collections.${common.domain}/public/resources.json
dataQualityChecksUrl: https://docs.google.com/spreadsheet/pub?key=0AjNtzhUIIHeNdHJOYk1SYWE4dU1BMWZmb2hiTjlYQlE&single=true&gid=0&output=csv
dataquality:
  apiKey: 28f72d39-6c8b-44fc-8184-cd81f6ea518a
  baseUrl: https://dataquality.ala.org.au/
  disableAllFiltersByDefault: false
  enabled: false
  expandFiltersByDefault: true
  learnmore_link: ''
  warningOn: false
defaultListView: ''
defaultLocale: en
disableCAS: false
doi:
  mintDoi: false
doiService:
  baseUrl: https://doi.ala.org.au
downloads:
  checklistDownloadUrl: ${common.protocol}://records-ws.${common.domain}/occurrences/facets/download
  customSections:
    misc: qualityAssertions,miscellaneousFields
  defaultDownloadFormat: dwc
  dwcExtraFields: data_resource_uid
  fieldguideDownloadUrl: ''
  indexedDownloadUrl: ${common.protocol}://records-ws.${common.domain}/occurrences/offline/download
  indexedFieldsUrl: ${common.protocol}://records-ws.${common.domain}/index/fields
  legacy:
    defaultFields: id,data_resource_uid,data_resource,license,catalogue_number,taxon_concept_lsid,raw_taxon_name,raw_common_name,taxon_name,rank,common_name,kingdom,phylum,class,order,family,genus,species,subspecies,institution_code,collection_code,locality,raw_latitude,raw_longitude,raw_datum,latitude,longitude,datum,coordinate_precision,coordinate_uncertainty,country,state,cl959,min_elevation_d,max_elevation_d,min_depth_d,max_depth_d,individual_count,recorded_by,year,month,day,verbatim_event_date,basis_of_record,raw_basis_of_record,sex,preparations,information_withheld,data_generalizations,outlier_layer,taxonomic_kosher,geospatial_kosher"
  staticDownloadsUrl: ''
  termsOfUseUrl: ''
dwc:
  exclude: dataHubUid,dataProviderUid,institutionUid,year,month,day,left,right,provenance,taxonID,preferredFlag,outlierForLayers,speciesGroups,associatedMedia,images,userQualityAssertion,speciesHabitats,duplicationType,taxonomicIssues,subspeciesID,nameMatchMetric,sounds
ecodata:
  baseURL: ''
endpoints:
  enabled: false
events:
  enabled: false
  eventUrl: https://events.${common.domain}/?view=EVENTS&eventHierarchy=
  graphql: https://api.${common.domain}/event/graphql
exploreYourArea:
  lat: 51.0
  lng: 4.4
  location: Vlaanderen
#facets:
#  cached: species_group,species_subgroup,state,country,institution_uid,collection_uid,data_resource_uid
#  customOrder: ''
#  defaultColourBy: ''
#  defaultSelected: basis_of_record,taxon_name,collection_uid,data_resource_uid,year,species_group
#  exclude: ''
#  hide: ''
#  include: ''
#  includeDynamicFacets: false
#  limit: 100
#  max: 32
fieldguide:
  url: ''
filetype:
  shapefile:
    hidden: false
geocode:
  region: BE
google:
  apikey: get-a-google-api-key
grails:
  resources:
    work:
      dir: /data/ala-hub/cache
  serverURL: ${common.protocol}://records.${common.domain}
headerAndFooter:
  baseURL: ${common.protocol}://branding.${common.domain}
  version: 2
image:
  baseUrl: ${common.protocol}://images.${common.domain}
images:
  baseUrl: ${common.protocol}://images.${common.domain}
  images:
    metadataUrl: ''
  metadataUrl: ${common.protocol}://images.${common.domain}/image/details?imageId=
  viewerUrl: ${common.protocol}://images.${common.domain}/image/viewer?imageId=
info:
  app:
    description: Vlaams Biodiversiteitsportaal
largeDownloadRole: ROLE_LARGE_DOWNLOAD
layersservice:
  baseUrl: ${common.protocol}://spatial.${common.domain}/ws
  url: ${common.protocol}://spatial.${common.domain}/ws
logger:
  baseUrl: ${common.protocol}://logger.${common.domain}/service
loggerURL: ${common.protocol}://logger.${common.domain}/service
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
#map:
#  cloudmade:
#    key: BC9A493B41014CAABB98F0471D759707
#  defaultFacetMapColourBy: ''
#  defaultLatitude: 51.0
#  defaultLongitude: 4.4
#  defaultZoom: 9
#  height: 600
#  minimal:
#    url: https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png
#  overlay:
#    url: ${common.protocol}://spatial.${common.domain}/geoserver/gwc/service/wms
#  pointColour: df4a21
#  zoomOutsideScopedRegion: true
#mapdownloads:
#  baseLayers:
#    provincies:
#      displayName: Provincies
##      i18nCode: baselayer.states
#      name: provincies_wgs84
maxDownloadRecords: ''
mdba:
  basinChampions: https://biocollect.ala.org.au/mdba/project/index/4d15b4df-c05b-41bd-ac5b-8a65c9e37d17
  regions: ${common.protocol}://mdba-regions.ala.org.au/
organisation:
  baseUrl: ${common.homepage}
pdfgen:
  baseURL: ${common.protocol}://pdfgen.ala.org.au
privacyPolicy: ''
server:
  address: 0.0.0.0
  contextPath: ''
  port: 8080
serverName: ${common.protocol}://records.${common.domain}
sightings:
  baseUrl: ''
skin:
  attribution: ''
  dataQualityLink:
    show: false
    text: not set
    url: ''
  exploreUrl: ${common.protocol}://regions.${common.domain}/explore-by-location/
  favicon: ${common.protocol}://branding.${common.domain}/favicon.ico
  fluidLayout: true
  homeUrl: ${common.protocol}://www.${common.domain}
  layout: ala
  orgNameLong: Vlaams Biodiversiteitsportaal
  orgNameShort: VBP
  taxaLinks:
    baseUrl: ${common.protocol}://species.${common.domain}/species/
  useAlaBie: true
  useAlaImageService: true
  useAlaSpatialPortal: true
spatial:
  baseURL: ${common.protocol}://spatial.${common.domain}
  baseUrl: ${common.protocol}://spatial.${common.domain}
  params: ''
speciesList:
  baseURL: ${common.protocol}://lists.${common.domain}
#  preferredListName: ALA Preferred Species Images
#  preferredSpeciesListDruid: dr4778
speciesListToolUrl: ${common.protocol}://lists.${common.domain}/speciesListItem/list/
specieslist:
  baseUrl: ${common.protocol}://lists.${common.domain}/ws
#stateConservationListPath:
#  AustralianCapitalTerritory: /speciesListItem/list/dr649
#  NewSouthWales: /speciesListItem/list/dr650
#  NorthernTerritory: /speciesListItem/list/dr651
#  Queensland: /speciesListItem/list/dr652
#  SouthAustralia: /speciesListItem/list/dr653
#  Tasmania: /speciesListItem/list/dr654
#  Victoria: /speciesListItem/list/dr655
#  WesternAustralia: /speciesListItem/list/dr2201
supportEmail: support@${common.domain}
table:
  displayDynamicProperties: false
uriExclusionFilterPattern: /occurrences/shapeUpload,/images.*,/css.*,/js.*,.*json,/help/.*
uriFilterPattern: /admin/*,/alaAdmin/*,/download/*
useDownloadPlugin: true
userCharts: false
userDetails:
  url: ${common.protocol}://auth.${common.domain}/userdetails/

